// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/loginauditlog"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginAuditLogCreate is the builder for creating a LoginAuditLog entity.
type LoginAuditLogCreate struct {
	config
	mutation *LoginAuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *LoginAuditLogCreate) SetCreatedAt(v time.Time) *LoginAuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableCreatedAt(v *time.Time) *LoginAuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *LoginAuditLogCreate) SetTenantID(v uint32) *LoginAuditLogCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableTenantID(v *uint32) *LoginAuditLogCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetLoginIP sets the "login_ip" field.
func (_c *LoginAuditLogCreate) SetLoginIP(v string) *LoginAuditLogCreate {
	_c.mutation.SetLoginIP(v)
	return _c
}

// SetNillableLoginIP sets the "login_ip" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableLoginIP(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetLoginIP(*v)
	}
	return _c
}

// SetLoginMAC sets the "login_mac" field.
func (_c *LoginAuditLogCreate) SetLoginMAC(v string) *LoginAuditLogCreate {
	_c.mutation.SetLoginMAC(v)
	return _c
}

// SetNillableLoginMAC sets the "login_mac" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableLoginMAC(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetLoginMAC(*v)
	}
	return _c
}

// SetLoginTime sets the "login_time" field.
func (_c *LoginAuditLogCreate) SetLoginTime(v time.Time) *LoginAuditLogCreate {
	_c.mutation.SetLoginTime(v)
	return _c
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableLoginTime(v *time.Time) *LoginAuditLogCreate {
	if v != nil {
		_c.SetLoginTime(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *LoginAuditLogCreate) SetUserAgent(v string) *LoginAuditLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableUserAgent(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetBrowserName sets the "browser_name" field.
func (_c *LoginAuditLogCreate) SetBrowserName(v string) *LoginAuditLogCreate {
	_c.mutation.SetBrowserName(v)
	return _c
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableBrowserName(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetBrowserName(*v)
	}
	return _c
}

// SetBrowserVersion sets the "browser_version" field.
func (_c *LoginAuditLogCreate) SetBrowserVersion(v string) *LoginAuditLogCreate {
	_c.mutation.SetBrowserVersion(v)
	return _c
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableBrowserVersion(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetBrowserVersion(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *LoginAuditLogCreate) SetClientID(v string) *LoginAuditLogCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableClientID(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetClientID(*v)
	}
	return _c
}

// SetClientName sets the "client_name" field.
func (_c *LoginAuditLogCreate) SetClientName(v string) *LoginAuditLogCreate {
	_c.mutation.SetClientName(v)
	return _c
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableClientName(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetClientName(*v)
	}
	return _c
}

// SetOsName sets the "os_name" field.
func (_c *LoginAuditLogCreate) SetOsName(v string) *LoginAuditLogCreate {
	_c.mutation.SetOsName(v)
	return _c
}

// SetNillableOsName sets the "os_name" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableOsName(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetOsName(*v)
	}
	return _c
}

// SetOsVersion sets the "os_version" field.
func (_c *LoginAuditLogCreate) SetOsVersion(v string) *LoginAuditLogCreate {
	_c.mutation.SetOsVersion(v)
	return _c
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableOsVersion(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetOsVersion(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *LoginAuditLogCreate) SetUserID(v uint32) *LoginAuditLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableUserID(v *uint32) *LoginAuditLogCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *LoginAuditLogCreate) SetUsername(v string) *LoginAuditLogCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableUsername(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *LoginAuditLogCreate) SetStatusCode(v int32) *LoginAuditLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableStatusCode(v *int32) *LoginAuditLogCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *LoginAuditLogCreate) SetSuccess(v bool) *LoginAuditLogCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableSuccess(v *bool) *LoginAuditLogCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *LoginAuditLogCreate) SetReason(v string) *LoginAuditLogCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableReason(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *LoginAuditLogCreate) SetLocation(v string) *LoginAuditLogCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *LoginAuditLogCreate) SetNillableLocation(v *string) *LoginAuditLogCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LoginAuditLogCreate) SetID(v uint32) *LoginAuditLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the LoginAuditLogMutation object of the builder.
func (_c *LoginAuditLogCreate) Mutation() *LoginAuditLogMutation {
	return _c.mutation
}

// Save creates the LoginAuditLog in the database.
func (_c *LoginAuditLogCreate) Save(ctx context.Context) (*LoginAuditLog, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoginAuditLogCreate) SaveX(ctx context.Context) *LoginAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginAuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginAuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoginAuditLogCreate) check() error {
	if v, ok := _c.mutation.ID(); ok {
		if err := loginauditlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "LoginAuditLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *LoginAuditLogCreate) sqlSave(ctx context.Context) (*LoginAuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoginAuditLogCreate) createSpec() (*LoginAuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &LoginAuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loginauditlog.Table, sqlgraph.NewFieldSpec(loginauditlog.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(loginauditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(loginauditlog.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.LoginIP(); ok {
		_spec.SetField(loginauditlog.FieldLoginIP, field.TypeString, value)
		_node.LoginIP = &value
	}
	if value, ok := _c.mutation.LoginMAC(); ok {
		_spec.SetField(loginauditlog.FieldLoginMAC, field.TypeString, value)
		_node.LoginMAC = &value
	}
	if value, ok := _c.mutation.LoginTime(); ok {
		_spec.SetField(loginauditlog.FieldLoginTime, field.TypeTime, value)
		_node.LoginTime = &value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(loginauditlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.BrowserName(); ok {
		_spec.SetField(loginauditlog.FieldBrowserName, field.TypeString, value)
		_node.BrowserName = &value
	}
	if value, ok := _c.mutation.BrowserVersion(); ok {
		_spec.SetField(loginauditlog.FieldBrowserVersion, field.TypeString, value)
		_node.BrowserVersion = &value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(loginauditlog.FieldClientID, field.TypeString, value)
		_node.ClientID = &value
	}
	if value, ok := _c.mutation.ClientName(); ok {
		_spec.SetField(loginauditlog.FieldClientName, field.TypeString, value)
		_node.ClientName = &value
	}
	if value, ok := _c.mutation.OsName(); ok {
		_spec.SetField(loginauditlog.FieldOsName, field.TypeString, value)
		_node.OsName = &value
	}
	if value, ok := _c.mutation.OsVersion(); ok {
		_spec.SetField(loginauditlog.FieldOsVersion, field.TypeString, value)
		_node.OsVersion = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(loginauditlog.FieldUserID, field.TypeUint32, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(loginauditlog.FieldUsername, field.TypeString, value)
		_node.Username = &value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(loginauditlog.FieldStatusCode, field.TypeInt32, value)
		_node.StatusCode = &value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(loginauditlog.FieldSuccess, field.TypeBool, value)
		_node.Success = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(loginauditlog.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(loginauditlog.FieldLocation, field.TypeString, value)
		_node.Location = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LoginAuditLog.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LoginAuditLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LoginAuditLogCreate) OnConflict(opts ...sql.ConflictOption) *LoginAuditLogUpsertOne {
	_c.conflict = opts
	return &LoginAuditLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LoginAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LoginAuditLogCreate) OnConflictColumns(columns ...string) *LoginAuditLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LoginAuditLogUpsertOne{
		create: _c,
	}
}

type (
	// LoginAuditLogUpsertOne is the builder for "upsert"-ing
	//  one LoginAuditLog node.
	LoginAuditLogUpsertOne struct {
		create *LoginAuditLogCreate
	}

	// LoginAuditLogUpsert is the "OnConflict" setter.
	LoginAuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetLoginIP sets the "login_ip" field.
func (u *LoginAuditLogUpsert) SetLoginIP(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldLoginIP, v)
	return u
}

// UpdateLoginIP sets the "login_ip" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateLoginIP() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldLoginIP)
	return u
}

// ClearLoginIP clears the value of the "login_ip" field.
func (u *LoginAuditLogUpsert) ClearLoginIP() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldLoginIP)
	return u
}

// SetLoginMAC sets the "login_mac" field.
func (u *LoginAuditLogUpsert) SetLoginMAC(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldLoginMAC, v)
	return u
}

// UpdateLoginMAC sets the "login_mac" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateLoginMAC() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldLoginMAC)
	return u
}

// ClearLoginMAC clears the value of the "login_mac" field.
func (u *LoginAuditLogUpsert) ClearLoginMAC() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldLoginMAC)
	return u
}

// SetLoginTime sets the "login_time" field.
func (u *LoginAuditLogUpsert) SetLoginTime(v time.Time) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldLoginTime, v)
	return u
}

// UpdateLoginTime sets the "login_time" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateLoginTime() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldLoginTime)
	return u
}

// ClearLoginTime clears the value of the "login_time" field.
func (u *LoginAuditLogUpsert) ClearLoginTime() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldLoginTime)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *LoginAuditLogUpsert) SetUserAgent(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateUserAgent() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *LoginAuditLogUpsert) ClearUserAgent() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldUserAgent)
	return u
}

// SetBrowserName sets the "browser_name" field.
func (u *LoginAuditLogUpsert) SetBrowserName(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldBrowserName, v)
	return u
}

// UpdateBrowserName sets the "browser_name" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateBrowserName() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldBrowserName)
	return u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (u *LoginAuditLogUpsert) ClearBrowserName() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldBrowserName)
	return u
}

// SetBrowserVersion sets the "browser_version" field.
func (u *LoginAuditLogUpsert) SetBrowserVersion(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldBrowserVersion, v)
	return u
}

// UpdateBrowserVersion sets the "browser_version" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateBrowserVersion() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldBrowserVersion)
	return u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (u *LoginAuditLogUpsert) ClearBrowserVersion() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldBrowserVersion)
	return u
}

// SetClientID sets the "client_id" field.
func (u *LoginAuditLogUpsert) SetClientID(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateClientID() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldClientID)
	return u
}

// ClearClientID clears the value of the "client_id" field.
func (u *LoginAuditLogUpsert) ClearClientID() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldClientID)
	return u
}

// SetClientName sets the "client_name" field.
func (u *LoginAuditLogUpsert) SetClientName(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldClientName, v)
	return u
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateClientName() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldClientName)
	return u
}

// ClearClientName clears the value of the "client_name" field.
func (u *LoginAuditLogUpsert) ClearClientName() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldClientName)
	return u
}

// SetOsName sets the "os_name" field.
func (u *LoginAuditLogUpsert) SetOsName(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldOsName, v)
	return u
}

// UpdateOsName sets the "os_name" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateOsName() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldOsName)
	return u
}

// ClearOsName clears the value of the "os_name" field.
func (u *LoginAuditLogUpsert) ClearOsName() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldOsName)
	return u
}

// SetOsVersion sets the "os_version" field.
func (u *LoginAuditLogUpsert) SetOsVersion(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldOsVersion, v)
	return u
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateOsVersion() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldOsVersion)
	return u
}

// ClearOsVersion clears the value of the "os_version" field.
func (u *LoginAuditLogUpsert) ClearOsVersion() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldOsVersion)
	return u
}

// SetUserID sets the "user_id" field.
func (u *LoginAuditLogUpsert) SetUserID(v uint32) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateUserID() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *LoginAuditLogUpsert) AddUserID(v uint32) *LoginAuditLogUpsert {
	u.Add(loginauditlog.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *LoginAuditLogUpsert) ClearUserID() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldUserID)
	return u
}

// SetUsername sets the "username" field.
func (u *LoginAuditLogUpsert) SetUsername(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateUsername() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldUsername)
	return u
}

// ClearUsername clears the value of the "username" field.
func (u *LoginAuditLogUpsert) ClearUsername() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldUsername)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *LoginAuditLogUpsert) SetStatusCode(v int32) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateStatusCode() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *LoginAuditLogUpsert) AddStatusCode(v int32) *LoginAuditLogUpsert {
	u.Add(loginauditlog.FieldStatusCode, v)
	return u
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *LoginAuditLogUpsert) ClearStatusCode() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldStatusCode)
	return u
}

// SetSuccess sets the "success" field.
func (u *LoginAuditLogUpsert) SetSuccess(v bool) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldSuccess, v)
	return u
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateSuccess() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldSuccess)
	return u
}

// ClearSuccess clears the value of the "success" field.
func (u *LoginAuditLogUpsert) ClearSuccess() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldSuccess)
	return u
}

// SetReason sets the "reason" field.
func (u *LoginAuditLogUpsert) SetReason(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateReason() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *LoginAuditLogUpsert) ClearReason() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldReason)
	return u
}

// SetLocation sets the "location" field.
func (u *LoginAuditLogUpsert) SetLocation(v string) *LoginAuditLogUpsert {
	u.Set(loginauditlog.FieldLocation, v)
	return u
}

// UpdateLocation sets the "location" field to the value that was provided on create.
func (u *LoginAuditLogUpsert) UpdateLocation() *LoginAuditLogUpsert {
	u.SetExcluded(loginauditlog.FieldLocation)
	return u
}

// ClearLocation clears the value of the "location" field.
func (u *LoginAuditLogUpsert) ClearLocation() *LoginAuditLogUpsert {
	u.SetNull(loginauditlog.FieldLocation)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LoginAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(loginauditlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LoginAuditLogUpsertOne) UpdateNewValues() *LoginAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(loginauditlog.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(loginauditlog.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(loginauditlog.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LoginAuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LoginAuditLogUpsertOne) Ignore() *LoginAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LoginAuditLogUpsertOne) DoNothing() *LoginAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LoginAuditLogCreate.OnConflict
// documentation for more info.
func (u *LoginAuditLogUpsertOne) Update(set func(*LoginAuditLogUpsert)) *LoginAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LoginAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetLoginIP sets the "login_ip" field.
func (u *LoginAuditLogUpsertOne) SetLoginIP(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetLoginIP(v)
	})
}

// UpdateLoginIP sets the "login_ip" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateLoginIP() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateLoginIP()
	})
}

// ClearLoginIP clears the value of the "login_ip" field.
func (u *LoginAuditLogUpsertOne) ClearLoginIP() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearLoginIP()
	})
}

// SetLoginMAC sets the "login_mac" field.
func (u *LoginAuditLogUpsertOne) SetLoginMAC(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetLoginMAC(v)
	})
}

// UpdateLoginMAC sets the "login_mac" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateLoginMAC() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateLoginMAC()
	})
}

// ClearLoginMAC clears the value of the "login_mac" field.
func (u *LoginAuditLogUpsertOne) ClearLoginMAC() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearLoginMAC()
	})
}

// SetLoginTime sets the "login_time" field.
func (u *LoginAuditLogUpsertOne) SetLoginTime(v time.Time) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetLoginTime(v)
	})
}

// UpdateLoginTime sets the "login_time" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateLoginTime() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateLoginTime()
	})
}

// ClearLoginTime clears the value of the "login_time" field.
func (u *LoginAuditLogUpsertOne) ClearLoginTime() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearLoginTime()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *LoginAuditLogUpsertOne) SetUserAgent(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateUserAgent() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *LoginAuditLogUpsertOne) ClearUserAgent() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetBrowserName sets the "browser_name" field.
func (u *LoginAuditLogUpsertOne) SetBrowserName(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetBrowserName(v)
	})
}

// UpdateBrowserName sets the "browser_name" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateBrowserName() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateBrowserName()
	})
}

// ClearBrowserName clears the value of the "browser_name" field.
func (u *LoginAuditLogUpsertOne) ClearBrowserName() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearBrowserName()
	})
}

// SetBrowserVersion sets the "browser_version" field.
func (u *LoginAuditLogUpsertOne) SetBrowserVersion(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetBrowserVersion(v)
	})
}

// UpdateBrowserVersion sets the "browser_version" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateBrowserVersion() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateBrowserVersion()
	})
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (u *LoginAuditLogUpsertOne) ClearBrowserVersion() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearBrowserVersion()
	})
}

// SetClientID sets the "client_id" field.
func (u *LoginAuditLogUpsertOne) SetClientID(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateClientID() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateClientID()
	})
}

// ClearClientID clears the value of the "client_id" field.
func (u *LoginAuditLogUpsertOne) ClearClientID() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearClientID()
	})
}

// SetClientName sets the "client_name" field.
func (u *LoginAuditLogUpsertOne) SetClientName(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetClientName(v)
	})
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateClientName() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateClientName()
	})
}

// ClearClientName clears the value of the "client_name" field.
func (u *LoginAuditLogUpsertOne) ClearClientName() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearClientName()
	})
}

// SetOsName sets the "os_name" field.
func (u *LoginAuditLogUpsertOne) SetOsName(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetOsName(v)
	})
}

// UpdateOsName sets the "os_name" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateOsName() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateOsName()
	})
}

// ClearOsName clears the value of the "os_name" field.
func (u *LoginAuditLogUpsertOne) ClearOsName() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearOsName()
	})
}

// SetOsVersion sets the "os_version" field.
func (u *LoginAuditLogUpsertOne) SetOsVersion(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetOsVersion(v)
	})
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateOsVersion() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateOsVersion()
	})
}

// ClearOsVersion clears the value of the "os_version" field.
func (u *LoginAuditLogUpsertOne) ClearOsVersion() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearOsVersion()
	})
}

// SetUserID sets the "user_id" field.
func (u *LoginAuditLogUpsertOne) SetUserID(v uint32) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LoginAuditLogUpsertOne) AddUserID(v uint32) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateUserID() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *LoginAuditLogUpsertOne) ClearUserID() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetUsername sets the "username" field.
func (u *LoginAuditLogUpsertOne) SetUsername(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateUsername() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateUsername()
	})
}

// ClearUsername clears the value of the "username" field.
func (u *LoginAuditLogUpsertOne) ClearUsername() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearUsername()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *LoginAuditLogUpsertOne) SetStatusCode(v int32) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *LoginAuditLogUpsertOne) AddStatusCode(v int32) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateStatusCode() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *LoginAuditLogUpsertOne) ClearStatusCode() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearStatusCode()
	})
}

// SetSuccess sets the "success" field.
func (u *LoginAuditLogUpsertOne) SetSuccess(v bool) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateSuccess() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateSuccess()
	})
}

// ClearSuccess clears the value of the "success" field.
func (u *LoginAuditLogUpsertOne) ClearSuccess() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearSuccess()
	})
}

// SetReason sets the "reason" field.
func (u *LoginAuditLogUpsertOne) SetReason(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateReason() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *LoginAuditLogUpsertOne) ClearReason() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearReason()
	})
}

// SetLocation sets the "location" field.
func (u *LoginAuditLogUpsertOne) SetLocation(v string) *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetLocation(v)
	})
}

// UpdateLocation sets the "location" field to the value that was provided on create.
func (u *LoginAuditLogUpsertOne) UpdateLocation() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateLocation()
	})
}

// ClearLocation clears the value of the "location" field.
func (u *LoginAuditLogUpsertOne) ClearLocation() *LoginAuditLogUpsertOne {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearLocation()
	})
}

// Exec executes the query.
func (u *LoginAuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LoginAuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LoginAuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LoginAuditLogUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LoginAuditLogUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LoginAuditLogCreateBulk is the builder for creating many LoginAuditLog entities in bulk.
type LoginAuditLogCreateBulk struct {
	config
	err      error
	builders []*LoginAuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the LoginAuditLog entities in the database.
func (_c *LoginAuditLogCreateBulk) Save(ctx context.Context) ([]*LoginAuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LoginAuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoginAuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoginAuditLogCreateBulk) SaveX(ctx context.Context) []*LoginAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginAuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginAuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LoginAuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LoginAuditLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LoginAuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *LoginAuditLogUpsertBulk {
	_c.conflict = opts
	return &LoginAuditLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LoginAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LoginAuditLogCreateBulk) OnConflictColumns(columns ...string) *LoginAuditLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LoginAuditLogUpsertBulk{
		create: _c,
	}
}

// LoginAuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of LoginAuditLog nodes.
type LoginAuditLogUpsertBulk struct {
	create *LoginAuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LoginAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(loginauditlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LoginAuditLogUpsertBulk) UpdateNewValues() *LoginAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(loginauditlog.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(loginauditlog.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(loginauditlog.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LoginAuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LoginAuditLogUpsertBulk) Ignore() *LoginAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LoginAuditLogUpsertBulk) DoNothing() *LoginAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LoginAuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *LoginAuditLogUpsertBulk) Update(set func(*LoginAuditLogUpsert)) *LoginAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LoginAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetLoginIP sets the "login_ip" field.
func (u *LoginAuditLogUpsertBulk) SetLoginIP(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetLoginIP(v)
	})
}

// UpdateLoginIP sets the "login_ip" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateLoginIP() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateLoginIP()
	})
}

// ClearLoginIP clears the value of the "login_ip" field.
func (u *LoginAuditLogUpsertBulk) ClearLoginIP() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearLoginIP()
	})
}

// SetLoginMAC sets the "login_mac" field.
func (u *LoginAuditLogUpsertBulk) SetLoginMAC(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetLoginMAC(v)
	})
}

// UpdateLoginMAC sets the "login_mac" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateLoginMAC() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateLoginMAC()
	})
}

// ClearLoginMAC clears the value of the "login_mac" field.
func (u *LoginAuditLogUpsertBulk) ClearLoginMAC() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearLoginMAC()
	})
}

// SetLoginTime sets the "login_time" field.
func (u *LoginAuditLogUpsertBulk) SetLoginTime(v time.Time) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetLoginTime(v)
	})
}

// UpdateLoginTime sets the "login_time" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateLoginTime() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateLoginTime()
	})
}

// ClearLoginTime clears the value of the "login_time" field.
func (u *LoginAuditLogUpsertBulk) ClearLoginTime() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearLoginTime()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *LoginAuditLogUpsertBulk) SetUserAgent(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateUserAgent() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *LoginAuditLogUpsertBulk) ClearUserAgent() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetBrowserName sets the "browser_name" field.
func (u *LoginAuditLogUpsertBulk) SetBrowserName(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetBrowserName(v)
	})
}

// UpdateBrowserName sets the "browser_name" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateBrowserName() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateBrowserName()
	})
}

// ClearBrowserName clears the value of the "browser_name" field.
func (u *LoginAuditLogUpsertBulk) ClearBrowserName() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearBrowserName()
	})
}

// SetBrowserVersion sets the "browser_version" field.
func (u *LoginAuditLogUpsertBulk) SetBrowserVersion(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetBrowserVersion(v)
	})
}

// UpdateBrowserVersion sets the "browser_version" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateBrowserVersion() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateBrowserVersion()
	})
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (u *LoginAuditLogUpsertBulk) ClearBrowserVersion() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearBrowserVersion()
	})
}

// SetClientID sets the "client_id" field.
func (u *LoginAuditLogUpsertBulk) SetClientID(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateClientID() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateClientID()
	})
}

// ClearClientID clears the value of the "client_id" field.
func (u *LoginAuditLogUpsertBulk) ClearClientID() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearClientID()
	})
}

// SetClientName sets the "client_name" field.
func (u *LoginAuditLogUpsertBulk) SetClientName(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetClientName(v)
	})
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateClientName() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateClientName()
	})
}

// ClearClientName clears the value of the "client_name" field.
func (u *LoginAuditLogUpsertBulk) ClearClientName() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearClientName()
	})
}

// SetOsName sets the "os_name" field.
func (u *LoginAuditLogUpsertBulk) SetOsName(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetOsName(v)
	})
}

// UpdateOsName sets the "os_name" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateOsName() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateOsName()
	})
}

// ClearOsName clears the value of the "os_name" field.
func (u *LoginAuditLogUpsertBulk) ClearOsName() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearOsName()
	})
}

// SetOsVersion sets the "os_version" field.
func (u *LoginAuditLogUpsertBulk) SetOsVersion(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetOsVersion(v)
	})
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateOsVersion() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateOsVersion()
	})
}

// ClearOsVersion clears the value of the "os_version" field.
func (u *LoginAuditLogUpsertBulk) ClearOsVersion() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearOsVersion()
	})
}

// SetUserID sets the "user_id" field.
func (u *LoginAuditLogUpsertBulk) SetUserID(v uint32) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LoginAuditLogUpsertBulk) AddUserID(v uint32) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateUserID() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *LoginAuditLogUpsertBulk) ClearUserID() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetUsername sets the "username" field.
func (u *LoginAuditLogUpsertBulk) SetUsername(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateUsername() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateUsername()
	})
}

// ClearUsername clears the value of the "username" field.
func (u *LoginAuditLogUpsertBulk) ClearUsername() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearUsername()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *LoginAuditLogUpsertBulk) SetStatusCode(v int32) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *LoginAuditLogUpsertBulk) AddStatusCode(v int32) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateStatusCode() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *LoginAuditLogUpsertBulk) ClearStatusCode() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearStatusCode()
	})
}

// SetSuccess sets the "success" field.
func (u *LoginAuditLogUpsertBulk) SetSuccess(v bool) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateSuccess() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateSuccess()
	})
}

// ClearSuccess clears the value of the "success" field.
func (u *LoginAuditLogUpsertBulk) ClearSuccess() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearSuccess()
	})
}

// SetReason sets the "reason" field.
func (u *LoginAuditLogUpsertBulk) SetReason(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateReason() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *LoginAuditLogUpsertBulk) ClearReason() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearReason()
	})
}

// SetLocation sets the "location" field.
func (u *LoginAuditLogUpsertBulk) SetLocation(v string) *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.SetLocation(v)
	})
}

// UpdateLocation sets the "location" field to the value that was provided on create.
func (u *LoginAuditLogUpsertBulk) UpdateLocation() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.UpdateLocation()
	})
}

// ClearLocation clears the value of the "location" field.
func (u *LoginAuditLogUpsertBulk) ClearLocation() *LoginAuditLogUpsertBulk {
	return u.Update(func(s *LoginAuditLogUpsert) {
		s.ClearLocation()
	})
}

// Exec executes the query.
func (u *LoginAuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LoginAuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LoginAuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LoginAuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
