// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/loginauditlog"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginAuditLogUpdate is the builder for updating LoginAuditLog entities.
type LoginAuditLogUpdate struct {
	config
	hooks     []Hook
	mutation  *LoginAuditLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LoginAuditLogUpdate builder.
func (_u *LoginAuditLogUpdate) Where(ps ...predicate.LoginAuditLog) *LoginAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLoginIP sets the "login_ip" field.
func (_u *LoginAuditLogUpdate) SetLoginIP(v string) *LoginAuditLogUpdate {
	_u.mutation.SetLoginIP(v)
	return _u
}

// SetNillableLoginIP sets the "login_ip" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableLoginIP(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetLoginIP(*v)
	}
	return _u
}

// ClearLoginIP clears the value of the "login_ip" field.
func (_u *LoginAuditLogUpdate) ClearLoginIP() *LoginAuditLogUpdate {
	_u.mutation.ClearLoginIP()
	return _u
}

// SetLoginMAC sets the "login_mac" field.
func (_u *LoginAuditLogUpdate) SetLoginMAC(v string) *LoginAuditLogUpdate {
	_u.mutation.SetLoginMAC(v)
	return _u
}

// SetNillableLoginMAC sets the "login_mac" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableLoginMAC(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetLoginMAC(*v)
	}
	return _u
}

// ClearLoginMAC clears the value of the "login_mac" field.
func (_u *LoginAuditLogUpdate) ClearLoginMAC() *LoginAuditLogUpdate {
	_u.mutation.ClearLoginMAC()
	return _u
}

// SetLoginTime sets the "login_time" field.
func (_u *LoginAuditLogUpdate) SetLoginTime(v time.Time) *LoginAuditLogUpdate {
	_u.mutation.SetLoginTime(v)
	return _u
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableLoginTime(v *time.Time) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetLoginTime(*v)
	}
	return _u
}

// ClearLoginTime clears the value of the "login_time" field.
func (_u *LoginAuditLogUpdate) ClearLoginTime() *LoginAuditLogUpdate {
	_u.mutation.ClearLoginTime()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *LoginAuditLogUpdate) SetUserAgent(v string) *LoginAuditLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableUserAgent(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *LoginAuditLogUpdate) ClearUserAgent() *LoginAuditLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetBrowserName sets the "browser_name" field.
func (_u *LoginAuditLogUpdate) SetBrowserName(v string) *LoginAuditLogUpdate {
	_u.mutation.SetBrowserName(v)
	return _u
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableBrowserName(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetBrowserName(*v)
	}
	return _u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (_u *LoginAuditLogUpdate) ClearBrowserName() *LoginAuditLogUpdate {
	_u.mutation.ClearBrowserName()
	return _u
}

// SetBrowserVersion sets the "browser_version" field.
func (_u *LoginAuditLogUpdate) SetBrowserVersion(v string) *LoginAuditLogUpdate {
	_u.mutation.SetBrowserVersion(v)
	return _u
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableBrowserVersion(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetBrowserVersion(*v)
	}
	return _u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (_u *LoginAuditLogUpdate) ClearBrowserVersion() *LoginAuditLogUpdate {
	_u.mutation.ClearBrowserVersion()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *LoginAuditLogUpdate) SetClientID(v string) *LoginAuditLogUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableClientID(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *LoginAuditLogUpdate) ClearClientID() *LoginAuditLogUpdate {
	_u.mutation.ClearClientID()
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *LoginAuditLogUpdate) SetClientName(v string) *LoginAuditLogUpdate {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableClientName(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// ClearClientName clears the value of the "client_name" field.
func (_u *LoginAuditLogUpdate) ClearClientName() *LoginAuditLogUpdate {
	_u.mutation.ClearClientName()
	return _u
}

// SetOsName sets the "os_name" field.
func (_u *LoginAuditLogUpdate) SetOsName(v string) *LoginAuditLogUpdate {
	_u.mutation.SetOsName(v)
	return _u
}

// SetNillableOsName sets the "os_name" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableOsName(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetOsName(*v)
	}
	return _u
}

// ClearOsName clears the value of the "os_name" field.
func (_u *LoginAuditLogUpdate) ClearOsName() *LoginAuditLogUpdate {
	_u.mutation.ClearOsName()
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *LoginAuditLogUpdate) SetOsVersion(v string) *LoginAuditLogUpdate {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableOsVersion(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// ClearOsVersion clears the value of the "os_version" field.
func (_u *LoginAuditLogUpdate) ClearOsVersion() *LoginAuditLogUpdate {
	_u.mutation.ClearOsVersion()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LoginAuditLogUpdate) SetUserID(v uint32) *LoginAuditLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableUserID(v *uint32) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LoginAuditLogUpdate) AddUserID(v int32) *LoginAuditLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *LoginAuditLogUpdate) ClearUserID() *LoginAuditLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *LoginAuditLogUpdate) SetUsername(v string) *LoginAuditLogUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableUsername(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *LoginAuditLogUpdate) ClearUsername() *LoginAuditLogUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *LoginAuditLogUpdate) SetStatusCode(v int32) *LoginAuditLogUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableStatusCode(v *int32) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *LoginAuditLogUpdate) AddStatusCode(v int32) *LoginAuditLogUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *LoginAuditLogUpdate) ClearStatusCode() *LoginAuditLogUpdate {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LoginAuditLogUpdate) SetSuccess(v bool) *LoginAuditLogUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableSuccess(v *bool) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// ClearSuccess clears the value of the "success" field.
func (_u *LoginAuditLogUpdate) ClearSuccess() *LoginAuditLogUpdate {
	_u.mutation.ClearSuccess()
	return _u
}

// SetReason sets the "reason" field.
func (_u *LoginAuditLogUpdate) SetReason(v string) *LoginAuditLogUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableReason(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *LoginAuditLogUpdate) ClearReason() *LoginAuditLogUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetLocation sets the "location" field.
func (_u *LoginAuditLogUpdate) SetLocation(v string) *LoginAuditLogUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *LoginAuditLogUpdate) SetNillableLocation(v *string) *LoginAuditLogUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *LoginAuditLogUpdate) ClearLocation() *LoginAuditLogUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// Mutation returns the LoginAuditLogMutation object of the builder.
func (_u *LoginAuditLogUpdate) Mutation() *LoginAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoginAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoginAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LoginAuditLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LoginAuditLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LoginAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(loginauditlog.Table, loginauditlog.Columns, sqlgraph.NewFieldSpec(loginauditlog.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(loginauditlog.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(loginauditlog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.LoginIP(); ok {
		_spec.SetField(loginauditlog.FieldLoginIP, field.TypeString, value)
	}
	if _u.mutation.LoginIPCleared() {
		_spec.ClearField(loginauditlog.FieldLoginIP, field.TypeString)
	}
	if value, ok := _u.mutation.LoginMAC(); ok {
		_spec.SetField(loginauditlog.FieldLoginMAC, field.TypeString, value)
	}
	if _u.mutation.LoginMACCleared() {
		_spec.ClearField(loginauditlog.FieldLoginMAC, field.TypeString)
	}
	if value, ok := _u.mutation.LoginTime(); ok {
		_spec.SetField(loginauditlog.FieldLoginTime, field.TypeTime, value)
	}
	if _u.mutation.LoginTimeCleared() {
		_spec.ClearField(loginauditlog.FieldLoginTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(loginauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(loginauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserName(); ok {
		_spec.SetField(loginauditlog.FieldBrowserName, field.TypeString, value)
	}
	if _u.mutation.BrowserNameCleared() {
		_spec.ClearField(loginauditlog.FieldBrowserName, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserVersion(); ok {
		_spec.SetField(loginauditlog.FieldBrowserVersion, field.TypeString, value)
	}
	if _u.mutation.BrowserVersionCleared() {
		_spec.ClearField(loginauditlog.FieldBrowserVersion, field.TypeString)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(loginauditlog.FieldClientID, field.TypeString, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(loginauditlog.FieldClientID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(loginauditlog.FieldClientName, field.TypeString, value)
	}
	if _u.mutation.ClientNameCleared() {
		_spec.ClearField(loginauditlog.FieldClientName, field.TypeString)
	}
	if value, ok := _u.mutation.OsName(); ok {
		_spec.SetField(loginauditlog.FieldOsName, field.TypeString, value)
	}
	if _u.mutation.OsNameCleared() {
		_spec.ClearField(loginauditlog.FieldOsName, field.TypeString)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(loginauditlog.FieldOsVersion, field.TypeString, value)
	}
	if _u.mutation.OsVersionCleared() {
		_spec.ClearField(loginauditlog.FieldOsVersion, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(loginauditlog.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(loginauditlog.FieldUserID, field.TypeUint32, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(loginauditlog.FieldUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(loginauditlog.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(loginauditlog.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(loginauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(loginauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(loginauditlog.FieldStatusCode, field.TypeInt32)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(loginauditlog.FieldSuccess, field.TypeBool, value)
	}
	if _u.mutation.SuccessCleared() {
		_spec.ClearField(loginauditlog.FieldSuccess, field.TypeBool)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(loginauditlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(loginauditlog.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(loginauditlog.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(loginauditlog.FieldLocation, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoginAuditLogUpdateOne is the builder for updating a single LoginAuditLog entity.
type LoginAuditLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LoginAuditLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetLoginIP sets the "login_ip" field.
func (_u *LoginAuditLogUpdateOne) SetLoginIP(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetLoginIP(v)
	return _u
}

// SetNillableLoginIP sets the "login_ip" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableLoginIP(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetLoginIP(*v)
	}
	return _u
}

// ClearLoginIP clears the value of the "login_ip" field.
func (_u *LoginAuditLogUpdateOne) ClearLoginIP() *LoginAuditLogUpdateOne {
	_u.mutation.ClearLoginIP()
	return _u
}

// SetLoginMAC sets the "login_mac" field.
func (_u *LoginAuditLogUpdateOne) SetLoginMAC(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetLoginMAC(v)
	return _u
}

// SetNillableLoginMAC sets the "login_mac" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableLoginMAC(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetLoginMAC(*v)
	}
	return _u
}

// ClearLoginMAC clears the value of the "login_mac" field.
func (_u *LoginAuditLogUpdateOne) ClearLoginMAC() *LoginAuditLogUpdateOne {
	_u.mutation.ClearLoginMAC()
	return _u
}

// SetLoginTime sets the "login_time" field.
func (_u *LoginAuditLogUpdateOne) SetLoginTime(v time.Time) *LoginAuditLogUpdateOne {
	_u.mutation.SetLoginTime(v)
	return _u
}

// SetNillableLoginTime sets the "login_time" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableLoginTime(v *time.Time) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetLoginTime(*v)
	}
	return _u
}

// ClearLoginTime clears the value of the "login_time" field.
func (_u *LoginAuditLogUpdateOne) ClearLoginTime() *LoginAuditLogUpdateOne {
	_u.mutation.ClearLoginTime()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *LoginAuditLogUpdateOne) SetUserAgent(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableUserAgent(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *LoginAuditLogUpdateOne) ClearUserAgent() *LoginAuditLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetBrowserName sets the "browser_name" field.
func (_u *LoginAuditLogUpdateOne) SetBrowserName(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetBrowserName(v)
	return _u
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableBrowserName(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetBrowserName(*v)
	}
	return _u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (_u *LoginAuditLogUpdateOne) ClearBrowserName() *LoginAuditLogUpdateOne {
	_u.mutation.ClearBrowserName()
	return _u
}

// SetBrowserVersion sets the "browser_version" field.
func (_u *LoginAuditLogUpdateOne) SetBrowserVersion(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetBrowserVersion(v)
	return _u
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableBrowserVersion(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetBrowserVersion(*v)
	}
	return _u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (_u *LoginAuditLogUpdateOne) ClearBrowserVersion() *LoginAuditLogUpdateOne {
	_u.mutation.ClearBrowserVersion()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *LoginAuditLogUpdateOne) SetClientID(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableClientID(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *LoginAuditLogUpdateOne) ClearClientID() *LoginAuditLogUpdateOne {
	_u.mutation.ClearClientID()
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *LoginAuditLogUpdateOne) SetClientName(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableClientName(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// ClearClientName clears the value of the "client_name" field.
func (_u *LoginAuditLogUpdateOne) ClearClientName() *LoginAuditLogUpdateOne {
	_u.mutation.ClearClientName()
	return _u
}

// SetOsName sets the "os_name" field.
func (_u *LoginAuditLogUpdateOne) SetOsName(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetOsName(v)
	return _u
}

// SetNillableOsName sets the "os_name" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableOsName(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetOsName(*v)
	}
	return _u
}

// ClearOsName clears the value of the "os_name" field.
func (_u *LoginAuditLogUpdateOne) ClearOsName() *LoginAuditLogUpdateOne {
	_u.mutation.ClearOsName()
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *LoginAuditLogUpdateOne) SetOsVersion(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableOsVersion(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// ClearOsVersion clears the value of the "os_version" field.
func (_u *LoginAuditLogUpdateOne) ClearOsVersion() *LoginAuditLogUpdateOne {
	_u.mutation.ClearOsVersion()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LoginAuditLogUpdateOne) SetUserID(v uint32) *LoginAuditLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableUserID(v *uint32) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LoginAuditLogUpdateOne) AddUserID(v int32) *LoginAuditLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *LoginAuditLogUpdateOne) ClearUserID() *LoginAuditLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *LoginAuditLogUpdateOne) SetUsername(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableUsername(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *LoginAuditLogUpdateOne) ClearUsername() *LoginAuditLogUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *LoginAuditLogUpdateOne) SetStatusCode(v int32) *LoginAuditLogUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableStatusCode(v *int32) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *LoginAuditLogUpdateOne) AddStatusCode(v int32) *LoginAuditLogUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *LoginAuditLogUpdateOne) ClearStatusCode() *LoginAuditLogUpdateOne {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LoginAuditLogUpdateOne) SetSuccess(v bool) *LoginAuditLogUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableSuccess(v *bool) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// ClearSuccess clears the value of the "success" field.
func (_u *LoginAuditLogUpdateOne) ClearSuccess() *LoginAuditLogUpdateOne {
	_u.mutation.ClearSuccess()
	return _u
}

// SetReason sets the "reason" field.
func (_u *LoginAuditLogUpdateOne) SetReason(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableReason(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *LoginAuditLogUpdateOne) ClearReason() *LoginAuditLogUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetLocation sets the "location" field.
func (_u *LoginAuditLogUpdateOne) SetLocation(v string) *LoginAuditLogUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *LoginAuditLogUpdateOne) SetNillableLocation(v *string) *LoginAuditLogUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *LoginAuditLogUpdateOne) ClearLocation() *LoginAuditLogUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// Mutation returns the LoginAuditLogMutation object of the builder.
func (_u *LoginAuditLogUpdateOne) Mutation() *LoginAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the LoginAuditLogUpdate builder.
func (_u *LoginAuditLogUpdateOne) Where(ps ...predicate.LoginAuditLog) *LoginAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoginAuditLogUpdateOne) Select(field string, fields ...string) *LoginAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LoginAuditLog entity.
func (_u *LoginAuditLogUpdateOne) Save(ctx context.Context) (*LoginAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginAuditLogUpdateOne) SaveX(ctx context.Context) *LoginAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoginAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LoginAuditLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LoginAuditLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LoginAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *LoginAuditLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(loginauditlog.Table, loginauditlog.Columns, sqlgraph.NewFieldSpec(loginauditlog.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LoginAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginauditlog.FieldID)
		for _, f := range fields {
			if !loginauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loginauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(loginauditlog.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(loginauditlog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.LoginIP(); ok {
		_spec.SetField(loginauditlog.FieldLoginIP, field.TypeString, value)
	}
	if _u.mutation.LoginIPCleared() {
		_spec.ClearField(loginauditlog.FieldLoginIP, field.TypeString)
	}
	if value, ok := _u.mutation.LoginMAC(); ok {
		_spec.SetField(loginauditlog.FieldLoginMAC, field.TypeString, value)
	}
	if _u.mutation.LoginMACCleared() {
		_spec.ClearField(loginauditlog.FieldLoginMAC, field.TypeString)
	}
	if value, ok := _u.mutation.LoginTime(); ok {
		_spec.SetField(loginauditlog.FieldLoginTime, field.TypeTime, value)
	}
	if _u.mutation.LoginTimeCleared() {
		_spec.ClearField(loginauditlog.FieldLoginTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(loginauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(loginauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserName(); ok {
		_spec.SetField(loginauditlog.FieldBrowserName, field.TypeString, value)
	}
	if _u.mutation.BrowserNameCleared() {
		_spec.ClearField(loginauditlog.FieldBrowserName, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserVersion(); ok {
		_spec.SetField(loginauditlog.FieldBrowserVersion, field.TypeString, value)
	}
	if _u.mutation.BrowserVersionCleared() {
		_spec.ClearField(loginauditlog.FieldBrowserVersion, field.TypeString)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(loginauditlog.FieldClientID, field.TypeString, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(loginauditlog.FieldClientID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(loginauditlog.FieldClientName, field.TypeString, value)
	}
	if _u.mutation.ClientNameCleared() {
		_spec.ClearField(loginauditlog.FieldClientName, field.TypeString)
	}
	if value, ok := _u.mutation.OsName(); ok {
		_spec.SetField(loginauditlog.FieldOsName, field.TypeString, value)
	}
	if _u.mutation.OsNameCleared() {
		_spec.ClearField(loginauditlog.FieldOsName, field.TypeString)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(loginauditlog.FieldOsVersion, field.TypeString, value)
	}
	if _u.mutation.OsVersionCleared() {
		_spec.ClearField(loginauditlog.FieldOsVersion, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(loginauditlog.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(loginauditlog.FieldUserID, field.TypeUint32, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(loginauditlog.FieldUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(loginauditlog.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(loginauditlog.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(loginauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(loginauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(loginauditlog.FieldStatusCode, field.TypeInt32)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(loginauditlog.FieldSuccess, field.TypeBool, value)
	}
	if _u.mutation.SuccessCleared() {
		_spec.ClearField(loginauditlog.FieldSuccess, field.TypeBool)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(loginauditlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(loginauditlog.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(loginauditlog.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(loginauditlog.FieldLocation, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &LoginAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
