// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/operationauditlog"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OperationAuditLogUpdate is the builder for updating OperationAuditLog entities.
type OperationAuditLogUpdate struct {
	config
	hooks     []Hook
	mutation  *OperationAuditLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OperationAuditLogUpdate builder.
func (_u *OperationAuditLogUpdate) Where(ps ...predicate.OperationAuditLog) *OperationAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *OperationAuditLogUpdate) SetRequestID(v string) *OperationAuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableRequestID(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *OperationAuditLogUpdate) ClearRequestID() *OperationAuditLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetMethod sets the "method" field.
func (_u *OperationAuditLogUpdate) SetMethod(v string) *OperationAuditLogUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableMethod(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *OperationAuditLogUpdate) ClearMethod() *OperationAuditLogUpdate {
	_u.mutation.ClearMethod()
	return _u
}

// SetOperation sets the "operation" field.
func (_u *OperationAuditLogUpdate) SetOperation(v string) *OperationAuditLogUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableOperation(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// ClearOperation clears the value of the "operation" field.
func (_u *OperationAuditLogUpdate) ClearOperation() *OperationAuditLogUpdate {
	_u.mutation.ClearOperation()
	return _u
}

// SetPath sets the "path" field.
func (_u *OperationAuditLogUpdate) SetPath(v string) *OperationAuditLogUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillablePath(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *OperationAuditLogUpdate) ClearPath() *OperationAuditLogUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetReferer sets the "referer" field.
func (_u *OperationAuditLogUpdate) SetReferer(v string) *OperationAuditLogUpdate {
	_u.mutation.SetReferer(v)
	return _u
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableReferer(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetReferer(*v)
	}
	return _u
}

// ClearReferer clears the value of the "referer" field.
func (_u *OperationAuditLogUpdate) ClearReferer() *OperationAuditLogUpdate {
	_u.mutation.ClearReferer()
	return _u
}

// SetRequestURI sets the "request_uri" field.
func (_u *OperationAuditLogUpdate) SetRequestURI(v string) *OperationAuditLogUpdate {
	_u.mutation.SetRequestURI(v)
	return _u
}

// SetNillableRequestURI sets the "request_uri" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableRequestURI(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetRequestURI(*v)
	}
	return _u
}

// ClearRequestURI clears the value of the "request_uri" field.
func (_u *OperationAuditLogUpdate) ClearRequestURI() *OperationAuditLogUpdate {
	_u.mutation.ClearRequestURI()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *OperationAuditLogUpdate) SetRequestBody(v string) *OperationAuditLogUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableRequestBody(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *OperationAuditLogUpdate) ClearRequestBody() *OperationAuditLogUpdate {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetRequestHeader sets the "request_header" field.
func (_u *OperationAuditLogUpdate) SetRequestHeader(v string) *OperationAuditLogUpdate {
	_u.mutation.SetRequestHeader(v)
	return _u
}

// SetNillableRequestHeader sets the "request_header" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableRequestHeader(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetRequestHeader(*v)
	}
	return _u
}

// ClearRequestHeader clears the value of the "request_header" field.
func (_u *OperationAuditLogUpdate) ClearRequestHeader() *OperationAuditLogUpdate {
	_u.mutation.ClearRequestHeader()
	return _u
}

// SetResponse sets the "response" field.
func (_u *OperationAuditLogUpdate) SetResponse(v string) *OperationAuditLogUpdate {
	_u.mutation.SetResponse(v)
	return _u
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableResponse(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetResponse(*v)
	}
	return _u
}

// ClearResponse clears the value of the "response" field.
func (_u *OperationAuditLogUpdate) ClearResponse() *OperationAuditLogUpdate {
	_u.mutation.ClearResponse()
	return _u
}

// SetCostTime sets the "cost_time" field.
func (_u *OperationAuditLogUpdate) SetCostTime(v float64) *OperationAuditLogUpdate {
	_u.mutation.ResetCostTime()
	_u.mutation.SetCostTime(v)
	return _u
}

// SetNillableCostTime sets the "cost_time" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableCostTime(v *float64) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetCostTime(*v)
	}
	return _u
}

// AddCostTime adds value to the "cost_time" field.
func (_u *OperationAuditLogUpdate) AddCostTime(v float64) *OperationAuditLogUpdate {
	_u.mutation.AddCostTime(v)
	return _u
}

// ClearCostTime clears the value of the "cost_time" field.
func (_u *OperationAuditLogUpdate) ClearCostTime() *OperationAuditLogUpdate {
	_u.mutation.ClearCostTime()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OperationAuditLogUpdate) SetUserID(v uint32) *OperationAuditLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableUserID(v *uint32) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OperationAuditLogUpdate) AddUserID(v int32) *OperationAuditLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OperationAuditLogUpdate) ClearUserID() *OperationAuditLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *OperationAuditLogUpdate) SetUsername(v string) *OperationAuditLogUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableUsername(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *OperationAuditLogUpdate) ClearUsername() *OperationAuditLogUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *OperationAuditLogUpdate) SetClientIP(v string) *OperationAuditLogUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableClientIP(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *OperationAuditLogUpdate) ClearClientIP() *OperationAuditLogUpdate {
	_u.mutation.ClearClientIP()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *OperationAuditLogUpdate) SetStatusCode(v int32) *OperationAuditLogUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableStatusCode(v *int32) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *OperationAuditLogUpdate) AddStatusCode(v int32) *OperationAuditLogUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *OperationAuditLogUpdate) ClearStatusCode() *OperationAuditLogUpdate {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetReason sets the "reason" field.
func (_u *OperationAuditLogUpdate) SetReason(v string) *OperationAuditLogUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableReason(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *OperationAuditLogUpdate) ClearReason() *OperationAuditLogUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *OperationAuditLogUpdate) SetSuccess(v bool) *OperationAuditLogUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableSuccess(v *bool) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// ClearSuccess clears the value of the "success" field.
func (_u *OperationAuditLogUpdate) ClearSuccess() *OperationAuditLogUpdate {
	_u.mutation.ClearSuccess()
	return _u
}

// SetLocation sets the "location" field.
func (_u *OperationAuditLogUpdate) SetLocation(v string) *OperationAuditLogUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableLocation(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *OperationAuditLogUpdate) ClearLocation() *OperationAuditLogUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *OperationAuditLogUpdate) SetUserAgent(v string) *OperationAuditLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableUserAgent(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *OperationAuditLogUpdate) ClearUserAgent() *OperationAuditLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetBrowserName sets the "browser_name" field.
func (_u *OperationAuditLogUpdate) SetBrowserName(v string) *OperationAuditLogUpdate {
	_u.mutation.SetBrowserName(v)
	return _u
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableBrowserName(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetBrowserName(*v)
	}
	return _u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (_u *OperationAuditLogUpdate) ClearBrowserName() *OperationAuditLogUpdate {
	_u.mutation.ClearBrowserName()
	return _u
}

// SetBrowserVersion sets the "browser_version" field.
func (_u *OperationAuditLogUpdate) SetBrowserVersion(v string) *OperationAuditLogUpdate {
	_u.mutation.SetBrowserVersion(v)
	return _u
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableBrowserVersion(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetBrowserVersion(*v)
	}
	return _u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (_u *OperationAuditLogUpdate) ClearBrowserVersion() *OperationAuditLogUpdate {
	_u.mutation.ClearBrowserVersion()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OperationAuditLogUpdate) SetClientID(v string) *OperationAuditLogUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableClientID(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *OperationAuditLogUpdate) ClearClientID() *OperationAuditLogUpdate {
	_u.mutation.ClearClientID()
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *OperationAuditLogUpdate) SetClientName(v string) *OperationAuditLogUpdate {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableClientName(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// ClearClientName clears the value of the "client_name" field.
func (_u *OperationAuditLogUpdate) ClearClientName() *OperationAuditLogUpdate {
	_u.mutation.ClearClientName()
	return _u
}

// SetOsName sets the "os_name" field.
func (_u *OperationAuditLogUpdate) SetOsName(v string) *OperationAuditLogUpdate {
	_u.mutation.SetOsName(v)
	return _u
}

// SetNillableOsName sets the "os_name" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableOsName(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetOsName(*v)
	}
	return _u
}

// ClearOsName clears the value of the "os_name" field.
func (_u *OperationAuditLogUpdate) ClearOsName() *OperationAuditLogUpdate {
	_u.mutation.ClearOsName()
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *OperationAuditLogUpdate) SetOsVersion(v string) *OperationAuditLogUpdate {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *OperationAuditLogUpdate) SetNillableOsVersion(v *string) *OperationAuditLogUpdate {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// ClearOsVersion clears the value of the "os_version" field.
func (_u *OperationAuditLogUpdate) ClearOsVersion() *OperationAuditLogUpdate {
	_u.mutation.ClearOsVersion()
	return _u
}

// Mutation returns the OperationAuditLogMutation object of the builder.
func (_u *OperationAuditLogUpdate) Mutation() *OperationAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OperationAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OperationAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OperationAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OperationAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OperationAuditLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OperationAuditLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OperationAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(operationauditlog.Table, operationauditlog.Columns, sqlgraph.NewFieldSpec(operationauditlog.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(operationauditlog.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(operationauditlog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(operationauditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(operationauditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(operationauditlog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(operationauditlog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(operationauditlog.FieldOperation, field.TypeString, value)
	}
	if _u.mutation.OperationCleared() {
		_spec.ClearField(operationauditlog.FieldOperation, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(operationauditlog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(operationauditlog.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Referer(); ok {
		_spec.SetField(operationauditlog.FieldReferer, field.TypeString, value)
	}
	if _u.mutation.RefererCleared() {
		_spec.ClearField(operationauditlog.FieldReferer, field.TypeString)
	}
	if value, ok := _u.mutation.RequestURI(); ok {
		_spec.SetField(operationauditlog.FieldRequestURI, field.TypeString, value)
	}
	if _u.mutation.RequestURICleared() {
		_spec.ClearField(operationauditlog.FieldRequestURI, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(operationauditlog.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(operationauditlog.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.RequestHeader(); ok {
		_spec.SetField(operationauditlog.FieldRequestHeader, field.TypeString, value)
	}
	if _u.mutation.RequestHeaderCleared() {
		_spec.ClearField(operationauditlog.FieldRequestHeader, field.TypeString)
	}
	if value, ok := _u.mutation.Response(); ok {
		_spec.SetField(operationauditlog.FieldResponse, field.TypeString, value)
	}
	if _u.mutation.ResponseCleared() {
		_spec.ClearField(operationauditlog.FieldResponse, field.TypeString)
	}
	if value, ok := _u.mutation.CostTime(); ok {
		_spec.SetField(operationauditlog.FieldCostTime, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostTime(); ok {
		_spec.AddField(operationauditlog.FieldCostTime, field.TypeFloat64, value)
	}
	if _u.mutation.CostTimeCleared() {
		_spec.ClearField(operationauditlog.FieldCostTime, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(operationauditlog.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(operationauditlog.FieldUserID, field.TypeUint32, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(operationauditlog.FieldUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(operationauditlog.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(operationauditlog.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(operationauditlog.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(operationauditlog.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(operationauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(operationauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(operationauditlog.FieldStatusCode, field.TypeInt32)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(operationauditlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(operationauditlog.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(operationauditlog.FieldSuccess, field.TypeBool, value)
	}
	if _u.mutation.SuccessCleared() {
		_spec.ClearField(operationauditlog.FieldSuccess, field.TypeBool)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(operationauditlog.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(operationauditlog.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(operationauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(operationauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserName(); ok {
		_spec.SetField(operationauditlog.FieldBrowserName, field.TypeString, value)
	}
	if _u.mutation.BrowserNameCleared() {
		_spec.ClearField(operationauditlog.FieldBrowserName, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserVersion(); ok {
		_spec.SetField(operationauditlog.FieldBrowserVersion, field.TypeString, value)
	}
	if _u.mutation.BrowserVersionCleared() {
		_spec.ClearField(operationauditlog.FieldBrowserVersion, field.TypeString)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(operationauditlog.FieldClientID, field.TypeString, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(operationauditlog.FieldClientID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(operationauditlog.FieldClientName, field.TypeString, value)
	}
	if _u.mutation.ClientNameCleared() {
		_spec.ClearField(operationauditlog.FieldClientName, field.TypeString)
	}
	if value, ok := _u.mutation.OsName(); ok {
		_spec.SetField(operationauditlog.FieldOsName, field.TypeString, value)
	}
	if _u.mutation.OsNameCleared() {
		_spec.ClearField(operationauditlog.FieldOsName, field.TypeString)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(operationauditlog.FieldOsVersion, field.TypeString, value)
	}
	if _u.mutation.OsVersionCleared() {
		_spec.ClearField(operationauditlog.FieldOsVersion, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{operationauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OperationAuditLogUpdateOne is the builder for updating a single OperationAuditLog entity.
type OperationAuditLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OperationAuditLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRequestID sets the "request_id" field.
func (_u *OperationAuditLogUpdateOne) SetRequestID(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableRequestID(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *OperationAuditLogUpdateOne) ClearRequestID() *OperationAuditLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetMethod sets the "method" field.
func (_u *OperationAuditLogUpdateOne) SetMethod(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableMethod(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *OperationAuditLogUpdateOne) ClearMethod() *OperationAuditLogUpdateOne {
	_u.mutation.ClearMethod()
	return _u
}

// SetOperation sets the "operation" field.
func (_u *OperationAuditLogUpdateOne) SetOperation(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableOperation(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// ClearOperation clears the value of the "operation" field.
func (_u *OperationAuditLogUpdateOne) ClearOperation() *OperationAuditLogUpdateOne {
	_u.mutation.ClearOperation()
	return _u
}

// SetPath sets the "path" field.
func (_u *OperationAuditLogUpdateOne) SetPath(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillablePath(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *OperationAuditLogUpdateOne) ClearPath() *OperationAuditLogUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetReferer sets the "referer" field.
func (_u *OperationAuditLogUpdateOne) SetReferer(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetReferer(v)
	return _u
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableReferer(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetReferer(*v)
	}
	return _u
}

// ClearReferer clears the value of the "referer" field.
func (_u *OperationAuditLogUpdateOne) ClearReferer() *OperationAuditLogUpdateOne {
	_u.mutation.ClearReferer()
	return _u
}

// SetRequestURI sets the "request_uri" field.
func (_u *OperationAuditLogUpdateOne) SetRequestURI(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetRequestURI(v)
	return _u
}

// SetNillableRequestURI sets the "request_uri" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableRequestURI(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestURI(*v)
	}
	return _u
}

// ClearRequestURI clears the value of the "request_uri" field.
func (_u *OperationAuditLogUpdateOne) ClearRequestURI() *OperationAuditLogUpdateOne {
	_u.mutation.ClearRequestURI()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *OperationAuditLogUpdateOne) SetRequestBody(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableRequestBody(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *OperationAuditLogUpdateOne) ClearRequestBody() *OperationAuditLogUpdateOne {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetRequestHeader sets the "request_header" field.
func (_u *OperationAuditLogUpdateOne) SetRequestHeader(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetRequestHeader(v)
	return _u
}

// SetNillableRequestHeader sets the "request_header" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableRequestHeader(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestHeader(*v)
	}
	return _u
}

// ClearRequestHeader clears the value of the "request_header" field.
func (_u *OperationAuditLogUpdateOne) ClearRequestHeader() *OperationAuditLogUpdateOne {
	_u.mutation.ClearRequestHeader()
	return _u
}

// SetResponse sets the "response" field.
func (_u *OperationAuditLogUpdateOne) SetResponse(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetResponse(v)
	return _u
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableResponse(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetResponse(*v)
	}
	return _u
}

// ClearResponse clears the value of the "response" field.
func (_u *OperationAuditLogUpdateOne) ClearResponse() *OperationAuditLogUpdateOne {
	_u.mutation.ClearResponse()
	return _u
}

// SetCostTime sets the "cost_time" field.
func (_u *OperationAuditLogUpdateOne) SetCostTime(v float64) *OperationAuditLogUpdateOne {
	_u.mutation.ResetCostTime()
	_u.mutation.SetCostTime(v)
	return _u
}

// SetNillableCostTime sets the "cost_time" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableCostTime(v *float64) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetCostTime(*v)
	}
	return _u
}

// AddCostTime adds value to the "cost_time" field.
func (_u *OperationAuditLogUpdateOne) AddCostTime(v float64) *OperationAuditLogUpdateOne {
	_u.mutation.AddCostTime(v)
	return _u
}

// ClearCostTime clears the value of the "cost_time" field.
func (_u *OperationAuditLogUpdateOne) ClearCostTime() *OperationAuditLogUpdateOne {
	_u.mutation.ClearCostTime()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OperationAuditLogUpdateOne) SetUserID(v uint32) *OperationAuditLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableUserID(v *uint32) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OperationAuditLogUpdateOne) AddUserID(v int32) *OperationAuditLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OperationAuditLogUpdateOne) ClearUserID() *OperationAuditLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *OperationAuditLogUpdateOne) SetUsername(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableUsername(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *OperationAuditLogUpdateOne) ClearUsername() *OperationAuditLogUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *OperationAuditLogUpdateOne) SetClientIP(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableClientIP(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *OperationAuditLogUpdateOne) ClearClientIP() *OperationAuditLogUpdateOne {
	_u.mutation.ClearClientIP()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *OperationAuditLogUpdateOne) SetStatusCode(v int32) *OperationAuditLogUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableStatusCode(v *int32) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *OperationAuditLogUpdateOne) AddStatusCode(v int32) *OperationAuditLogUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// ClearStatusCode clears the value of the "status_code" field.
func (_u *OperationAuditLogUpdateOne) ClearStatusCode() *OperationAuditLogUpdateOne {
	_u.mutation.ClearStatusCode()
	return _u
}

// SetReason sets the "reason" field.
func (_u *OperationAuditLogUpdateOne) SetReason(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableReason(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *OperationAuditLogUpdateOne) ClearReason() *OperationAuditLogUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *OperationAuditLogUpdateOne) SetSuccess(v bool) *OperationAuditLogUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableSuccess(v *bool) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// ClearSuccess clears the value of the "success" field.
func (_u *OperationAuditLogUpdateOne) ClearSuccess() *OperationAuditLogUpdateOne {
	_u.mutation.ClearSuccess()
	return _u
}

// SetLocation sets the "location" field.
func (_u *OperationAuditLogUpdateOne) SetLocation(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableLocation(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *OperationAuditLogUpdateOne) ClearLocation() *OperationAuditLogUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *OperationAuditLogUpdateOne) SetUserAgent(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableUserAgent(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *OperationAuditLogUpdateOne) ClearUserAgent() *OperationAuditLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetBrowserName sets the "browser_name" field.
func (_u *OperationAuditLogUpdateOne) SetBrowserName(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetBrowserName(v)
	return _u
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableBrowserName(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetBrowserName(*v)
	}
	return _u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (_u *OperationAuditLogUpdateOne) ClearBrowserName() *OperationAuditLogUpdateOne {
	_u.mutation.ClearBrowserName()
	return _u
}

// SetBrowserVersion sets the "browser_version" field.
func (_u *OperationAuditLogUpdateOne) SetBrowserVersion(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetBrowserVersion(v)
	return _u
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableBrowserVersion(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetBrowserVersion(*v)
	}
	return _u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (_u *OperationAuditLogUpdateOne) ClearBrowserVersion() *OperationAuditLogUpdateOne {
	_u.mutation.ClearBrowserVersion()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OperationAuditLogUpdateOne) SetClientID(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableClientID(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *OperationAuditLogUpdateOne) ClearClientID() *OperationAuditLogUpdateOne {
	_u.mutation.ClearClientID()
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *OperationAuditLogUpdateOne) SetClientName(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableClientName(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// ClearClientName clears the value of the "client_name" field.
func (_u *OperationAuditLogUpdateOne) ClearClientName() *OperationAuditLogUpdateOne {
	_u.mutation.ClearClientName()
	return _u
}

// SetOsName sets the "os_name" field.
func (_u *OperationAuditLogUpdateOne) SetOsName(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetOsName(v)
	return _u
}

// SetNillableOsName sets the "os_name" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableOsName(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetOsName(*v)
	}
	return _u
}

// ClearOsName clears the value of the "os_name" field.
func (_u *OperationAuditLogUpdateOne) ClearOsName() *OperationAuditLogUpdateOne {
	_u.mutation.ClearOsName()
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *OperationAuditLogUpdateOne) SetOsVersion(v string) *OperationAuditLogUpdateOne {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *OperationAuditLogUpdateOne) SetNillableOsVersion(v *string) *OperationAuditLogUpdateOne {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// ClearOsVersion clears the value of the "os_version" field.
func (_u *OperationAuditLogUpdateOne) ClearOsVersion() *OperationAuditLogUpdateOne {
	_u.mutation.ClearOsVersion()
	return _u
}

// Mutation returns the OperationAuditLogMutation object of the builder.
func (_u *OperationAuditLogUpdateOne) Mutation() *OperationAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the OperationAuditLogUpdate builder.
func (_u *OperationAuditLogUpdateOne) Where(ps ...predicate.OperationAuditLog) *OperationAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OperationAuditLogUpdateOne) Select(field string, fields ...string) *OperationAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OperationAuditLog entity.
func (_u *OperationAuditLogUpdateOne) Save(ctx context.Context) (*OperationAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OperationAuditLogUpdateOne) SaveX(ctx context.Context) *OperationAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OperationAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OperationAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OperationAuditLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OperationAuditLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OperationAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *OperationAuditLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(operationauditlog.Table, operationauditlog.Columns, sqlgraph.NewFieldSpec(operationauditlog.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OperationAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, operationauditlog.FieldID)
		for _, f := range fields {
			if !operationauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != operationauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(operationauditlog.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(operationauditlog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(operationauditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(operationauditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(operationauditlog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(operationauditlog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(operationauditlog.FieldOperation, field.TypeString, value)
	}
	if _u.mutation.OperationCleared() {
		_spec.ClearField(operationauditlog.FieldOperation, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(operationauditlog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(operationauditlog.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Referer(); ok {
		_spec.SetField(operationauditlog.FieldReferer, field.TypeString, value)
	}
	if _u.mutation.RefererCleared() {
		_spec.ClearField(operationauditlog.FieldReferer, field.TypeString)
	}
	if value, ok := _u.mutation.RequestURI(); ok {
		_spec.SetField(operationauditlog.FieldRequestURI, field.TypeString, value)
	}
	if _u.mutation.RequestURICleared() {
		_spec.ClearField(operationauditlog.FieldRequestURI, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(operationauditlog.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(operationauditlog.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.RequestHeader(); ok {
		_spec.SetField(operationauditlog.FieldRequestHeader, field.TypeString, value)
	}
	if _u.mutation.RequestHeaderCleared() {
		_spec.ClearField(operationauditlog.FieldRequestHeader, field.TypeString)
	}
	if value, ok := _u.mutation.Response(); ok {
		_spec.SetField(operationauditlog.FieldResponse, field.TypeString, value)
	}
	if _u.mutation.ResponseCleared() {
		_spec.ClearField(operationauditlog.FieldResponse, field.TypeString)
	}
	if value, ok := _u.mutation.CostTime(); ok {
		_spec.SetField(operationauditlog.FieldCostTime, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostTime(); ok {
		_spec.AddField(operationauditlog.FieldCostTime, field.TypeFloat64, value)
	}
	if _u.mutation.CostTimeCleared() {
		_spec.ClearField(operationauditlog.FieldCostTime, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(operationauditlog.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(operationauditlog.FieldUserID, field.TypeUint32, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(operationauditlog.FieldUserID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(operationauditlog.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(operationauditlog.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(operationauditlog.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(operationauditlog.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(operationauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(operationauditlog.FieldStatusCode, field.TypeInt32, value)
	}
	if _u.mutation.StatusCodeCleared() {
		_spec.ClearField(operationauditlog.FieldStatusCode, field.TypeInt32)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(operationauditlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(operationauditlog.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(operationauditlog.FieldSuccess, field.TypeBool, value)
	}
	if _u.mutation.SuccessCleared() {
		_spec.ClearField(operationauditlog.FieldSuccess, field.TypeBool)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(operationauditlog.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(operationauditlog.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(operationauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(operationauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserName(); ok {
		_spec.SetField(operationauditlog.FieldBrowserName, field.TypeString, value)
	}
	if _u.mutation.BrowserNameCleared() {
		_spec.ClearField(operationauditlog.FieldBrowserName, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserVersion(); ok {
		_spec.SetField(operationauditlog.FieldBrowserVersion, field.TypeString, value)
	}
	if _u.mutation.BrowserVersionCleared() {
		_spec.ClearField(operationauditlog.FieldBrowserVersion, field.TypeString)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(operationauditlog.FieldClientID, field.TypeString, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(operationauditlog.FieldClientID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(operationauditlog.FieldClientName, field.TypeString, value)
	}
	if _u.mutation.ClientNameCleared() {
		_spec.ClearField(operationauditlog.FieldClientName, field.TypeString)
	}
	if value, ok := _u.mutation.OsName(); ok {
		_spec.SetField(operationauditlog.FieldOsName, field.TypeString, value)
	}
	if _u.mutation.OsNameCleared() {
		_spec.ClearField(operationauditlog.FieldOsName, field.TypeString)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(operationauditlog.FieldOsVersion, field.TypeString, value)
	}
	if _u.mutation.OsVersionCleared() {
		_spec.ClearField(operationauditlog.FieldOsVersion, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &OperationAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{operationauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
