// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/operationauditlog"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OperationAuditLogCreate is the builder for creating a OperationAuditLog entity.
type OperationAuditLogCreate struct {
	config
	mutation *OperationAuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OperationAuditLogCreate) SetCreatedAt(v time.Time) *OperationAuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableCreatedAt(v *time.Time) *OperationAuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *OperationAuditLogCreate) SetTenantID(v uint32) *OperationAuditLogCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableTenantID(v *uint32) *OperationAuditLogCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *OperationAuditLogCreate) SetRequestID(v string) *OperationAuditLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableRequestID(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *OperationAuditLogCreate) SetMethod(v string) *OperationAuditLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableMethod(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetOperation sets the "operation" field.
func (_c *OperationAuditLogCreate) SetOperation(v string) *OperationAuditLogCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableOperation(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetOperation(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *OperationAuditLogCreate) SetPath(v string) *OperationAuditLogCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillablePath(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetReferer sets the "referer" field.
func (_c *OperationAuditLogCreate) SetReferer(v string) *OperationAuditLogCreate {
	_c.mutation.SetReferer(v)
	return _c
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableReferer(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetReferer(*v)
	}
	return _c
}

// SetRequestURI sets the "request_uri" field.
func (_c *OperationAuditLogCreate) SetRequestURI(v string) *OperationAuditLogCreate {
	_c.mutation.SetRequestURI(v)
	return _c
}

// SetNillableRequestURI sets the "request_uri" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableRequestURI(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetRequestURI(*v)
	}
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *OperationAuditLogCreate) SetRequestBody(v string) *OperationAuditLogCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableRequestBody(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetRequestBody(*v)
	}
	return _c
}

// SetRequestHeader sets the "request_header" field.
func (_c *OperationAuditLogCreate) SetRequestHeader(v string) *OperationAuditLogCreate {
	_c.mutation.SetRequestHeader(v)
	return _c
}

// SetNillableRequestHeader sets the "request_header" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableRequestHeader(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetRequestHeader(*v)
	}
	return _c
}

// SetResponse sets the "response" field.
func (_c *OperationAuditLogCreate) SetResponse(v string) *OperationAuditLogCreate {
	_c.mutation.SetResponse(v)
	return _c
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableResponse(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetResponse(*v)
	}
	return _c
}

// SetCostTime sets the "cost_time" field.
func (_c *OperationAuditLogCreate) SetCostTime(v float64) *OperationAuditLogCreate {
	_c.mutation.SetCostTime(v)
	return _c
}

// SetNillableCostTime sets the "cost_time" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableCostTime(v *float64) *OperationAuditLogCreate {
	if v != nil {
		_c.SetCostTime(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OperationAuditLogCreate) SetUserID(v uint32) *OperationAuditLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableUserID(v *uint32) *OperationAuditLogCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *OperationAuditLogCreate) SetUsername(v string) *OperationAuditLogCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableUsername(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetClientIP sets the "client_ip" field.
func (_c *OperationAuditLogCreate) SetClientIP(v string) *OperationAuditLogCreate {
	_c.mutation.SetClientIP(v)
	return _c
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableClientIP(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetClientIP(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *OperationAuditLogCreate) SetStatusCode(v int32) *OperationAuditLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableStatusCode(v *int32) *OperationAuditLogCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *OperationAuditLogCreate) SetReason(v string) *OperationAuditLogCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableReason(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *OperationAuditLogCreate) SetSuccess(v bool) *OperationAuditLogCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableSuccess(v *bool) *OperationAuditLogCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *OperationAuditLogCreate) SetLocation(v string) *OperationAuditLogCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableLocation(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *OperationAuditLogCreate) SetUserAgent(v string) *OperationAuditLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableUserAgent(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetBrowserName sets the "browser_name" field.
func (_c *OperationAuditLogCreate) SetBrowserName(v string) *OperationAuditLogCreate {
	_c.mutation.SetBrowserName(v)
	return _c
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableBrowserName(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetBrowserName(*v)
	}
	return _c
}

// SetBrowserVersion sets the "browser_version" field.
func (_c *OperationAuditLogCreate) SetBrowserVersion(v string) *OperationAuditLogCreate {
	_c.mutation.SetBrowserVersion(v)
	return _c
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableBrowserVersion(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetBrowserVersion(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OperationAuditLogCreate) SetClientID(v string) *OperationAuditLogCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableClientID(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetClientID(*v)
	}
	return _c
}

// SetClientName sets the "client_name" field.
func (_c *OperationAuditLogCreate) SetClientName(v string) *OperationAuditLogCreate {
	_c.mutation.SetClientName(v)
	return _c
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableClientName(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetClientName(*v)
	}
	return _c
}

// SetOsName sets the "os_name" field.
func (_c *OperationAuditLogCreate) SetOsName(v string) *OperationAuditLogCreate {
	_c.mutation.SetOsName(v)
	return _c
}

// SetNillableOsName sets the "os_name" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableOsName(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetOsName(*v)
	}
	return _c
}

// SetOsVersion sets the "os_version" field.
func (_c *OperationAuditLogCreate) SetOsVersion(v string) *OperationAuditLogCreate {
	_c.mutation.SetOsVersion(v)
	return _c
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_c *OperationAuditLogCreate) SetNillableOsVersion(v *string) *OperationAuditLogCreate {
	if v != nil {
		_c.SetOsVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OperationAuditLogCreate) SetID(v uint32) *OperationAuditLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OperationAuditLogMutation object of the builder.
func (_c *OperationAuditLogCreate) Mutation() *OperationAuditLogMutation {
	return _c.mutation
}

// Save creates the OperationAuditLog in the database.
func (_c *OperationAuditLogCreate) Save(ctx context.Context) (*OperationAuditLog, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OperationAuditLogCreate) SaveX(ctx context.Context) *OperationAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperationAuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperationAuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OperationAuditLogCreate) check() error {
	if v, ok := _c.mutation.ID(); ok {
		if err := operationauditlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "OperationAuditLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *OperationAuditLogCreate) sqlSave(ctx context.Context) (*OperationAuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OperationAuditLogCreate) createSpec() (*OperationAuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &OperationAuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(operationauditlog.Table, sqlgraph.NewFieldSpec(operationauditlog.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(operationauditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(operationauditlog.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(operationauditlog.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(operationauditlog.FieldMethod, field.TypeString, value)
		_node.Method = &value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(operationauditlog.FieldOperation, field.TypeString, value)
		_node.Operation = &value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(operationauditlog.FieldPath, field.TypeString, value)
		_node.Path = &value
	}
	if value, ok := _c.mutation.Referer(); ok {
		_spec.SetField(operationauditlog.FieldReferer, field.TypeString, value)
		_node.Referer = &value
	}
	if value, ok := _c.mutation.RequestURI(); ok {
		_spec.SetField(operationauditlog.FieldRequestURI, field.TypeString, value)
		_node.RequestURI = &value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(operationauditlog.FieldRequestBody, field.TypeString, value)
		_node.RequestBody = &value
	}
	if value, ok := _c.mutation.RequestHeader(); ok {
		_spec.SetField(operationauditlog.FieldRequestHeader, field.TypeString, value)
		_node.RequestHeader = &value
	}
	if value, ok := _c.mutation.Response(); ok {
		_spec.SetField(operationauditlog.FieldResponse, field.TypeString, value)
		_node.Response = &value
	}
	if value, ok := _c.mutation.CostTime(); ok {
		_spec.SetField(operationauditlog.FieldCostTime, field.TypeFloat64, value)
		_node.CostTime = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(operationauditlog.FieldUserID, field.TypeUint32, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(operationauditlog.FieldUsername, field.TypeString, value)
		_node.Username = &value
	}
	if value, ok := _c.mutation.ClientIP(); ok {
		_spec.SetField(operationauditlog.FieldClientIP, field.TypeString, value)
		_node.ClientIP = &value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(operationauditlog.FieldStatusCode, field.TypeInt32, value)
		_node.StatusCode = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(operationauditlog.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(operationauditlog.FieldSuccess, field.TypeBool, value)
		_node.Success = &value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(operationauditlog.FieldLocation, field.TypeString, value)
		_node.Location = &value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(operationauditlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.BrowserName(); ok {
		_spec.SetField(operationauditlog.FieldBrowserName, field.TypeString, value)
		_node.BrowserName = &value
	}
	if value, ok := _c.mutation.BrowserVersion(); ok {
		_spec.SetField(operationauditlog.FieldBrowserVersion, field.TypeString, value)
		_node.BrowserVersion = &value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(operationauditlog.FieldClientID, field.TypeString, value)
		_node.ClientID = &value
	}
	if value, ok := _c.mutation.ClientName(); ok {
		_spec.SetField(operationauditlog.FieldClientName, field.TypeString, value)
		_node.ClientName = &value
	}
	if value, ok := _c.mutation.OsName(); ok {
		_spec.SetField(operationauditlog.FieldOsName, field.TypeString, value)
		_node.OsName = &value
	}
	if value, ok := _c.mutation.OsVersion(); ok {
		_spec.SetField(operationauditlog.FieldOsVersion, field.TypeString, value)
		_node.OsVersion = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OperationAuditLog.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OperationAuditLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OperationAuditLogCreate) OnConflict(opts ...sql.ConflictOption) *OperationAuditLogUpsertOne {
	_c.conflict = opts
	return &OperationAuditLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OperationAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OperationAuditLogCreate) OnConflictColumns(columns ...string) *OperationAuditLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OperationAuditLogUpsertOne{
		create: _c,
	}
}

type (
	// OperationAuditLogUpsertOne is the builder for "upsert"-ing
	//  one OperationAuditLog node.
	OperationAuditLogUpsertOne struct {
		create *OperationAuditLogCreate
	}

	// OperationAuditLogUpsert is the "OnConflict" setter.
	OperationAuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *OperationAuditLogUpsert) SetRequestID(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateRequestID() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *OperationAuditLogUpsert) ClearRequestID() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldRequestID)
	return u
}

// SetMethod sets the "method" field.
func (u *OperationAuditLogUpsert) SetMethod(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldMethod, v)
	return u
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateMethod() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldMethod)
	return u
}

// ClearMethod clears the value of the "method" field.
func (u *OperationAuditLogUpsert) ClearMethod() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldMethod)
	return u
}

// SetOperation sets the "operation" field.
func (u *OperationAuditLogUpsert) SetOperation(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldOperation, v)
	return u
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateOperation() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldOperation)
	return u
}

// ClearOperation clears the value of the "operation" field.
func (u *OperationAuditLogUpsert) ClearOperation() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldOperation)
	return u
}

// SetPath sets the "path" field.
func (u *OperationAuditLogUpsert) SetPath(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdatePath() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldPath)
	return u
}

// ClearPath clears the value of the "path" field.
func (u *OperationAuditLogUpsert) ClearPath() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldPath)
	return u
}

// SetReferer sets the "referer" field.
func (u *OperationAuditLogUpsert) SetReferer(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldReferer, v)
	return u
}

// UpdateReferer sets the "referer" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateReferer() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldReferer)
	return u
}

// ClearReferer clears the value of the "referer" field.
func (u *OperationAuditLogUpsert) ClearReferer() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldReferer)
	return u
}

// SetRequestURI sets the "request_uri" field.
func (u *OperationAuditLogUpsert) SetRequestURI(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldRequestURI, v)
	return u
}

// UpdateRequestURI sets the "request_uri" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateRequestURI() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldRequestURI)
	return u
}

// ClearRequestURI clears the value of the "request_uri" field.
func (u *OperationAuditLogUpsert) ClearRequestURI() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldRequestURI)
	return u
}

// SetRequestBody sets the "request_body" field.
func (u *OperationAuditLogUpsert) SetRequestBody(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldRequestBody, v)
	return u
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateRequestBody() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldRequestBody)
	return u
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *OperationAuditLogUpsert) ClearRequestBody() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldRequestBody)
	return u
}

// SetRequestHeader sets the "request_header" field.
func (u *OperationAuditLogUpsert) SetRequestHeader(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldRequestHeader, v)
	return u
}

// UpdateRequestHeader sets the "request_header" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateRequestHeader() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldRequestHeader)
	return u
}

// ClearRequestHeader clears the value of the "request_header" field.
func (u *OperationAuditLogUpsert) ClearRequestHeader() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldRequestHeader)
	return u
}

// SetResponse sets the "response" field.
func (u *OperationAuditLogUpsert) SetResponse(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldResponse, v)
	return u
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateResponse() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldResponse)
	return u
}

// ClearResponse clears the value of the "response" field.
func (u *OperationAuditLogUpsert) ClearResponse() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldResponse)
	return u
}

// SetCostTime sets the "cost_time" field.
func (u *OperationAuditLogUpsert) SetCostTime(v float64) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldCostTime, v)
	return u
}

// UpdateCostTime sets the "cost_time" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateCostTime() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldCostTime)
	return u
}

// AddCostTime adds v to the "cost_time" field.
func (u *OperationAuditLogUpsert) AddCostTime(v float64) *OperationAuditLogUpsert {
	u.Add(operationauditlog.FieldCostTime, v)
	return u
}

// ClearCostTime clears the value of the "cost_time" field.
func (u *OperationAuditLogUpsert) ClearCostTime() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldCostTime)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OperationAuditLogUpsert) SetUserID(v uint32) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateUserID() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *OperationAuditLogUpsert) AddUserID(v uint32) *OperationAuditLogUpsert {
	u.Add(operationauditlog.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *OperationAuditLogUpsert) ClearUserID() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldUserID)
	return u
}

// SetUsername sets the "username" field.
func (u *OperationAuditLogUpsert) SetUsername(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateUsername() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldUsername)
	return u
}

// ClearUsername clears the value of the "username" field.
func (u *OperationAuditLogUpsert) ClearUsername() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldUsername)
	return u
}

// SetClientIP sets the "client_ip" field.
func (u *OperationAuditLogUpsert) SetClientIP(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldClientIP, v)
	return u
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateClientIP() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldClientIP)
	return u
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *OperationAuditLogUpsert) ClearClientIP() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldClientIP)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *OperationAuditLogUpsert) SetStatusCode(v int32) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateStatusCode() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *OperationAuditLogUpsert) AddStatusCode(v int32) *OperationAuditLogUpsert {
	u.Add(operationauditlog.FieldStatusCode, v)
	return u
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *OperationAuditLogUpsert) ClearStatusCode() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldStatusCode)
	return u
}

// SetReason sets the "reason" field.
func (u *OperationAuditLogUpsert) SetReason(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateReason() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *OperationAuditLogUpsert) ClearReason() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldReason)
	return u
}

// SetSuccess sets the "success" field.
func (u *OperationAuditLogUpsert) SetSuccess(v bool) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldSuccess, v)
	return u
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateSuccess() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldSuccess)
	return u
}

// ClearSuccess clears the value of the "success" field.
func (u *OperationAuditLogUpsert) ClearSuccess() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldSuccess)
	return u
}

// SetLocation sets the "location" field.
func (u *OperationAuditLogUpsert) SetLocation(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldLocation, v)
	return u
}

// UpdateLocation sets the "location" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateLocation() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldLocation)
	return u
}

// ClearLocation clears the value of the "location" field.
func (u *OperationAuditLogUpsert) ClearLocation() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldLocation)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *OperationAuditLogUpsert) SetUserAgent(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateUserAgent() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *OperationAuditLogUpsert) ClearUserAgent() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldUserAgent)
	return u
}

// SetBrowserName sets the "browser_name" field.
func (u *OperationAuditLogUpsert) SetBrowserName(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldBrowserName, v)
	return u
}

// UpdateBrowserName sets the "browser_name" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateBrowserName() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldBrowserName)
	return u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (u *OperationAuditLogUpsert) ClearBrowserName() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldBrowserName)
	return u
}

// SetBrowserVersion sets the "browser_version" field.
func (u *OperationAuditLogUpsert) SetBrowserVersion(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldBrowserVersion, v)
	return u
}

// UpdateBrowserVersion sets the "browser_version" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateBrowserVersion() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldBrowserVersion)
	return u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (u *OperationAuditLogUpsert) ClearBrowserVersion() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldBrowserVersion)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OperationAuditLogUpsert) SetClientID(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateClientID() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldClientID)
	return u
}

// ClearClientID clears the value of the "client_id" field.
func (u *OperationAuditLogUpsert) ClearClientID() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldClientID)
	return u
}

// SetClientName sets the "client_name" field.
func (u *OperationAuditLogUpsert) SetClientName(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldClientName, v)
	return u
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateClientName() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldClientName)
	return u
}

// ClearClientName clears the value of the "client_name" field.
func (u *OperationAuditLogUpsert) ClearClientName() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldClientName)
	return u
}

// SetOsName sets the "os_name" field.
func (u *OperationAuditLogUpsert) SetOsName(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldOsName, v)
	return u
}

// UpdateOsName sets the "os_name" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateOsName() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldOsName)
	return u
}

// ClearOsName clears the value of the "os_name" field.
func (u *OperationAuditLogUpsert) ClearOsName() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldOsName)
	return u
}

// SetOsVersion sets the "os_version" field.
func (u *OperationAuditLogUpsert) SetOsVersion(v string) *OperationAuditLogUpsert {
	u.Set(operationauditlog.FieldOsVersion, v)
	return u
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *OperationAuditLogUpsert) UpdateOsVersion() *OperationAuditLogUpsert {
	u.SetExcluded(operationauditlog.FieldOsVersion)
	return u
}

// ClearOsVersion clears the value of the "os_version" field.
func (u *OperationAuditLogUpsert) ClearOsVersion() *OperationAuditLogUpsert {
	u.SetNull(operationauditlog.FieldOsVersion)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OperationAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(operationauditlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OperationAuditLogUpsertOne) UpdateNewValues() *OperationAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(operationauditlog.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(operationauditlog.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(operationauditlog.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OperationAuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OperationAuditLogUpsertOne) Ignore() *OperationAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OperationAuditLogUpsertOne) DoNothing() *OperationAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OperationAuditLogCreate.OnConflict
// documentation for more info.
func (u *OperationAuditLogUpsertOne) Update(set func(*OperationAuditLogUpsert)) *OperationAuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OperationAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *OperationAuditLogUpsertOne) SetRequestID(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateRequestID() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *OperationAuditLogUpsertOne) ClearRequestID() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearRequestID()
	})
}

// SetMethod sets the "method" field.
func (u *OperationAuditLogUpsertOne) SetMethod(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateMethod() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateMethod()
	})
}

// ClearMethod clears the value of the "method" field.
func (u *OperationAuditLogUpsertOne) ClearMethod() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearMethod()
	})
}

// SetOperation sets the "operation" field.
func (u *OperationAuditLogUpsertOne) SetOperation(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateOperation() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateOperation()
	})
}

// ClearOperation clears the value of the "operation" field.
func (u *OperationAuditLogUpsertOne) ClearOperation() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearOperation()
	})
}

// SetPath sets the "path" field.
func (u *OperationAuditLogUpsertOne) SetPath(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdatePath() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *OperationAuditLogUpsertOne) ClearPath() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearPath()
	})
}

// SetReferer sets the "referer" field.
func (u *OperationAuditLogUpsertOne) SetReferer(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetReferer(v)
	})
}

// UpdateReferer sets the "referer" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateReferer() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateReferer()
	})
}

// ClearReferer clears the value of the "referer" field.
func (u *OperationAuditLogUpsertOne) ClearReferer() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearReferer()
	})
}

// SetRequestURI sets the "request_uri" field.
func (u *OperationAuditLogUpsertOne) SetRequestURI(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetRequestURI(v)
	})
}

// UpdateRequestURI sets the "request_uri" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateRequestURI() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateRequestURI()
	})
}

// ClearRequestURI clears the value of the "request_uri" field.
func (u *OperationAuditLogUpsertOne) ClearRequestURI() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearRequestURI()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *OperationAuditLogUpsertOne) SetRequestBody(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateRequestBody() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateRequestBody()
	})
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *OperationAuditLogUpsertOne) ClearRequestBody() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearRequestBody()
	})
}

// SetRequestHeader sets the "request_header" field.
func (u *OperationAuditLogUpsertOne) SetRequestHeader(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetRequestHeader(v)
	})
}

// UpdateRequestHeader sets the "request_header" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateRequestHeader() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateRequestHeader()
	})
}

// ClearRequestHeader clears the value of the "request_header" field.
func (u *OperationAuditLogUpsertOne) ClearRequestHeader() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearRequestHeader()
	})
}

// SetResponse sets the "response" field.
func (u *OperationAuditLogUpsertOne) SetResponse(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetResponse(v)
	})
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateResponse() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateResponse()
	})
}

// ClearResponse clears the value of the "response" field.
func (u *OperationAuditLogUpsertOne) ClearResponse() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearResponse()
	})
}

// SetCostTime sets the "cost_time" field.
func (u *OperationAuditLogUpsertOne) SetCostTime(v float64) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetCostTime(v)
	})
}

// AddCostTime adds v to the "cost_time" field.
func (u *OperationAuditLogUpsertOne) AddCostTime(v float64) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.AddCostTime(v)
	})
}

// UpdateCostTime sets the "cost_time" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateCostTime() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateCostTime()
	})
}

// ClearCostTime clears the value of the "cost_time" field.
func (u *OperationAuditLogUpsertOne) ClearCostTime() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearCostTime()
	})
}

// SetUserID sets the "user_id" field.
func (u *OperationAuditLogUpsertOne) SetUserID(v uint32) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OperationAuditLogUpsertOne) AddUserID(v uint32) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateUserID() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *OperationAuditLogUpsertOne) ClearUserID() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetUsername sets the "username" field.
func (u *OperationAuditLogUpsertOne) SetUsername(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateUsername() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateUsername()
	})
}

// ClearUsername clears the value of the "username" field.
func (u *OperationAuditLogUpsertOne) ClearUsername() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearUsername()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *OperationAuditLogUpsertOne) SetClientIP(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateClientIP() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateClientIP()
	})
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *OperationAuditLogUpsertOne) ClearClientIP() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearClientIP()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *OperationAuditLogUpsertOne) SetStatusCode(v int32) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *OperationAuditLogUpsertOne) AddStatusCode(v int32) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateStatusCode() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *OperationAuditLogUpsertOne) ClearStatusCode() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearStatusCode()
	})
}

// SetReason sets the "reason" field.
func (u *OperationAuditLogUpsertOne) SetReason(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateReason() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *OperationAuditLogUpsertOne) ClearReason() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearReason()
	})
}

// SetSuccess sets the "success" field.
func (u *OperationAuditLogUpsertOne) SetSuccess(v bool) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateSuccess() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateSuccess()
	})
}

// ClearSuccess clears the value of the "success" field.
func (u *OperationAuditLogUpsertOne) ClearSuccess() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearSuccess()
	})
}

// SetLocation sets the "location" field.
func (u *OperationAuditLogUpsertOne) SetLocation(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetLocation(v)
	})
}

// UpdateLocation sets the "location" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateLocation() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateLocation()
	})
}

// ClearLocation clears the value of the "location" field.
func (u *OperationAuditLogUpsertOne) ClearLocation() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearLocation()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *OperationAuditLogUpsertOne) SetUserAgent(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateUserAgent() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *OperationAuditLogUpsertOne) ClearUserAgent() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetBrowserName sets the "browser_name" field.
func (u *OperationAuditLogUpsertOne) SetBrowserName(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetBrowserName(v)
	})
}

// UpdateBrowserName sets the "browser_name" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateBrowserName() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateBrowserName()
	})
}

// ClearBrowserName clears the value of the "browser_name" field.
func (u *OperationAuditLogUpsertOne) ClearBrowserName() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearBrowserName()
	})
}

// SetBrowserVersion sets the "browser_version" field.
func (u *OperationAuditLogUpsertOne) SetBrowserVersion(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetBrowserVersion(v)
	})
}

// UpdateBrowserVersion sets the "browser_version" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateBrowserVersion() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateBrowserVersion()
	})
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (u *OperationAuditLogUpsertOne) ClearBrowserVersion() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearBrowserVersion()
	})
}

// SetClientID sets the "client_id" field.
func (u *OperationAuditLogUpsertOne) SetClientID(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateClientID() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateClientID()
	})
}

// ClearClientID clears the value of the "client_id" field.
func (u *OperationAuditLogUpsertOne) ClearClientID() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearClientID()
	})
}

// SetClientName sets the "client_name" field.
func (u *OperationAuditLogUpsertOne) SetClientName(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetClientName(v)
	})
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateClientName() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateClientName()
	})
}

// ClearClientName clears the value of the "client_name" field.
func (u *OperationAuditLogUpsertOne) ClearClientName() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearClientName()
	})
}

// SetOsName sets the "os_name" field.
func (u *OperationAuditLogUpsertOne) SetOsName(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetOsName(v)
	})
}

// UpdateOsName sets the "os_name" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateOsName() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateOsName()
	})
}

// ClearOsName clears the value of the "os_name" field.
func (u *OperationAuditLogUpsertOne) ClearOsName() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearOsName()
	})
}

// SetOsVersion sets the "os_version" field.
func (u *OperationAuditLogUpsertOne) SetOsVersion(v string) *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetOsVersion(v)
	})
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *OperationAuditLogUpsertOne) UpdateOsVersion() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateOsVersion()
	})
}

// ClearOsVersion clears the value of the "os_version" field.
func (u *OperationAuditLogUpsertOne) ClearOsVersion() *OperationAuditLogUpsertOne {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearOsVersion()
	})
}

// Exec executes the query.
func (u *OperationAuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OperationAuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OperationAuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OperationAuditLogUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OperationAuditLogUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OperationAuditLogCreateBulk is the builder for creating many OperationAuditLog entities in bulk.
type OperationAuditLogCreateBulk struct {
	config
	err      error
	builders []*OperationAuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the OperationAuditLog entities in the database.
func (_c *OperationAuditLogCreateBulk) Save(ctx context.Context) ([]*OperationAuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OperationAuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OperationAuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OperationAuditLogCreateBulk) SaveX(ctx context.Context) []*OperationAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OperationAuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OperationAuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OperationAuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OperationAuditLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OperationAuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *OperationAuditLogUpsertBulk {
	_c.conflict = opts
	return &OperationAuditLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OperationAuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OperationAuditLogCreateBulk) OnConflictColumns(columns ...string) *OperationAuditLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OperationAuditLogUpsertBulk{
		create: _c,
	}
}

// OperationAuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of OperationAuditLog nodes.
type OperationAuditLogUpsertBulk struct {
	create *OperationAuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OperationAuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(operationauditlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OperationAuditLogUpsertBulk) UpdateNewValues() *OperationAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(operationauditlog.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(operationauditlog.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(operationauditlog.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OperationAuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OperationAuditLogUpsertBulk) Ignore() *OperationAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OperationAuditLogUpsertBulk) DoNothing() *OperationAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OperationAuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *OperationAuditLogUpsertBulk) Update(set func(*OperationAuditLogUpsert)) *OperationAuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OperationAuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *OperationAuditLogUpsertBulk) SetRequestID(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateRequestID() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *OperationAuditLogUpsertBulk) ClearRequestID() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearRequestID()
	})
}

// SetMethod sets the "method" field.
func (u *OperationAuditLogUpsertBulk) SetMethod(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateMethod() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateMethod()
	})
}

// ClearMethod clears the value of the "method" field.
func (u *OperationAuditLogUpsertBulk) ClearMethod() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearMethod()
	})
}

// SetOperation sets the "operation" field.
func (u *OperationAuditLogUpsertBulk) SetOperation(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateOperation() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateOperation()
	})
}

// ClearOperation clears the value of the "operation" field.
func (u *OperationAuditLogUpsertBulk) ClearOperation() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearOperation()
	})
}

// SetPath sets the "path" field.
func (u *OperationAuditLogUpsertBulk) SetPath(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdatePath() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdatePath()
	})
}

// ClearPath clears the value of the "path" field.
func (u *OperationAuditLogUpsertBulk) ClearPath() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearPath()
	})
}

// SetReferer sets the "referer" field.
func (u *OperationAuditLogUpsertBulk) SetReferer(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetReferer(v)
	})
}

// UpdateReferer sets the "referer" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateReferer() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateReferer()
	})
}

// ClearReferer clears the value of the "referer" field.
func (u *OperationAuditLogUpsertBulk) ClearReferer() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearReferer()
	})
}

// SetRequestURI sets the "request_uri" field.
func (u *OperationAuditLogUpsertBulk) SetRequestURI(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetRequestURI(v)
	})
}

// UpdateRequestURI sets the "request_uri" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateRequestURI() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateRequestURI()
	})
}

// ClearRequestURI clears the value of the "request_uri" field.
func (u *OperationAuditLogUpsertBulk) ClearRequestURI() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearRequestURI()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *OperationAuditLogUpsertBulk) SetRequestBody(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateRequestBody() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateRequestBody()
	})
}

// ClearRequestBody clears the value of the "request_body" field.
func (u *OperationAuditLogUpsertBulk) ClearRequestBody() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearRequestBody()
	})
}

// SetRequestHeader sets the "request_header" field.
func (u *OperationAuditLogUpsertBulk) SetRequestHeader(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetRequestHeader(v)
	})
}

// UpdateRequestHeader sets the "request_header" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateRequestHeader() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateRequestHeader()
	})
}

// ClearRequestHeader clears the value of the "request_header" field.
func (u *OperationAuditLogUpsertBulk) ClearRequestHeader() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearRequestHeader()
	})
}

// SetResponse sets the "response" field.
func (u *OperationAuditLogUpsertBulk) SetResponse(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetResponse(v)
	})
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateResponse() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateResponse()
	})
}

// ClearResponse clears the value of the "response" field.
func (u *OperationAuditLogUpsertBulk) ClearResponse() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearResponse()
	})
}

// SetCostTime sets the "cost_time" field.
func (u *OperationAuditLogUpsertBulk) SetCostTime(v float64) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetCostTime(v)
	})
}

// AddCostTime adds v to the "cost_time" field.
func (u *OperationAuditLogUpsertBulk) AddCostTime(v float64) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.AddCostTime(v)
	})
}

// UpdateCostTime sets the "cost_time" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateCostTime() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateCostTime()
	})
}

// ClearCostTime clears the value of the "cost_time" field.
func (u *OperationAuditLogUpsertBulk) ClearCostTime() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearCostTime()
	})
}

// SetUserID sets the "user_id" field.
func (u *OperationAuditLogUpsertBulk) SetUserID(v uint32) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OperationAuditLogUpsertBulk) AddUserID(v uint32) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateUserID() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *OperationAuditLogUpsertBulk) ClearUserID() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetUsername sets the "username" field.
func (u *OperationAuditLogUpsertBulk) SetUsername(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateUsername() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateUsername()
	})
}

// ClearUsername clears the value of the "username" field.
func (u *OperationAuditLogUpsertBulk) ClearUsername() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearUsername()
	})
}

// SetClientIP sets the "client_ip" field.
func (u *OperationAuditLogUpsertBulk) SetClientIP(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetClientIP(v)
	})
}

// UpdateClientIP sets the "client_ip" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateClientIP() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateClientIP()
	})
}

// ClearClientIP clears the value of the "client_ip" field.
func (u *OperationAuditLogUpsertBulk) ClearClientIP() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearClientIP()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *OperationAuditLogUpsertBulk) SetStatusCode(v int32) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *OperationAuditLogUpsertBulk) AddStatusCode(v int32) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateStatusCode() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateStatusCode()
	})
}

// ClearStatusCode clears the value of the "status_code" field.
func (u *OperationAuditLogUpsertBulk) ClearStatusCode() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearStatusCode()
	})
}

// SetReason sets the "reason" field.
func (u *OperationAuditLogUpsertBulk) SetReason(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateReason() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *OperationAuditLogUpsertBulk) ClearReason() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearReason()
	})
}

// SetSuccess sets the "success" field.
func (u *OperationAuditLogUpsertBulk) SetSuccess(v bool) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateSuccess() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateSuccess()
	})
}

// ClearSuccess clears the value of the "success" field.
func (u *OperationAuditLogUpsertBulk) ClearSuccess() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearSuccess()
	})
}

// SetLocation sets the "location" field.
func (u *OperationAuditLogUpsertBulk) SetLocation(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetLocation(v)
	})
}

// UpdateLocation sets the "location" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateLocation() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateLocation()
	})
}

// ClearLocation clears the value of the "location" field.
func (u *OperationAuditLogUpsertBulk) ClearLocation() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearLocation()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *OperationAuditLogUpsertBulk) SetUserAgent(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateUserAgent() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *OperationAuditLogUpsertBulk) ClearUserAgent() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetBrowserName sets the "browser_name" field.
func (u *OperationAuditLogUpsertBulk) SetBrowserName(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetBrowserName(v)
	})
}

// UpdateBrowserName sets the "browser_name" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateBrowserName() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateBrowserName()
	})
}

// ClearBrowserName clears the value of the "browser_name" field.
func (u *OperationAuditLogUpsertBulk) ClearBrowserName() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearBrowserName()
	})
}

// SetBrowserVersion sets the "browser_version" field.
func (u *OperationAuditLogUpsertBulk) SetBrowserVersion(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetBrowserVersion(v)
	})
}

// UpdateBrowserVersion sets the "browser_version" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateBrowserVersion() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateBrowserVersion()
	})
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (u *OperationAuditLogUpsertBulk) ClearBrowserVersion() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearBrowserVersion()
	})
}

// SetClientID sets the "client_id" field.
func (u *OperationAuditLogUpsertBulk) SetClientID(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateClientID() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateClientID()
	})
}

// ClearClientID clears the value of the "client_id" field.
func (u *OperationAuditLogUpsertBulk) ClearClientID() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearClientID()
	})
}

// SetClientName sets the "client_name" field.
func (u *OperationAuditLogUpsertBulk) SetClientName(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetClientName(v)
	})
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateClientName() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateClientName()
	})
}

// ClearClientName clears the value of the "client_name" field.
func (u *OperationAuditLogUpsertBulk) ClearClientName() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearClientName()
	})
}

// SetOsName sets the "os_name" field.
func (u *OperationAuditLogUpsertBulk) SetOsName(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetOsName(v)
	})
}

// UpdateOsName sets the "os_name" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateOsName() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateOsName()
	})
}

// ClearOsName clears the value of the "os_name" field.
func (u *OperationAuditLogUpsertBulk) ClearOsName() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearOsName()
	})
}

// SetOsVersion sets the "os_version" field.
func (u *OperationAuditLogUpsertBulk) SetOsVersion(v string) *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.SetOsVersion(v)
	})
}

// UpdateOsVersion sets the "os_version" field to the value that was provided on create.
func (u *OperationAuditLogUpsertBulk) UpdateOsVersion() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.UpdateOsVersion()
	})
}

// ClearOsVersion clears the value of the "os_version" field.
func (u *OperationAuditLogUpsertBulk) ClearOsVersion() *OperationAuditLogUpsertBulk {
	return u.Update(func(s *OperationAuditLogUpsert) {
		s.ClearOsVersion()
	})
}

// Exec executes the query.
func (u *OperationAuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OperationAuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OperationAuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OperationAuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
