// Code generated by ent, DO NOT EDIT.

package rolemetadata

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the rolemetadata type in the database.
	Label = "role_metadata"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// FieldIsTemplate holds the string denoting the is_template field in the database.
	FieldIsTemplate = "is_template"
	// FieldTemplateFor holds the string denoting the template_for field in the database.
	FieldTemplateFor = "template_for"
	// FieldTemplateVersion holds the string denoting the template_version field in the database.
	FieldTemplateVersion = "template_version"
	// FieldLastSyncedVersion holds the string denoting the last_synced_version field in the database.
	FieldLastSyncedVersion = "last_synced_version"
	// FieldCustomOverrides holds the string denoting the custom_overrides field in the database.
	FieldCustomOverrides = "custom_overrides"
	// Table holds the table name of the rolemetadata in the database.
	Table = "sys_role_metadata"
)

// Columns holds all SQL columns for rolemetadata fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldRoleID,
	FieldIsTemplate,
	FieldTemplateFor,
	FieldTemplateVersion,
	FieldLastSyncedVersion,
	FieldCustomOverrides,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsTemplate holds the default value on creation for the "is_template" field.
	DefaultIsTemplate bool
	// DefaultTemplateVersion holds the default value on creation for the "template_version" field.
	DefaultTemplateVersion int32
	// DefaultLastSyncedVersion holds the default value on creation for the "last_synced_version" field.
	DefaultLastSyncedVersion int32
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// OrderOption defines the ordering options for the RoleMetadata queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByRoleID orders the results by the role_id field.
func ByRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleID, opts...).ToFunc()
}

// ByIsTemplate orders the results by the is_template field.
func ByIsTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsTemplate, opts...).ToFunc()
}

// ByTemplateFor orders the results by the template_for field.
func ByTemplateFor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateFor, opts...).ToFunc()
}

// ByTemplateVersion orders the results by the template_version field.
func ByTemplateVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateVersion, opts...).ToFunc()
}

// ByLastSyncedVersion orders the results by the last_synced_version field.
func ByLastSyncedVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedVersion, opts...).ToFunc()
}
