// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysAdminLoginLogsColumns holds the columns for the "sys_admin_login_logs" table.
	SysAdminLoginLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "login_ip", Type: field.TypeString, Nullable: true, Comment: "登录IP地址"},
		{Name: "login_mac", Type: field.TypeString, Nullable: true, Comment: "登录MAC地址"},
		{Name: "login_time", Type: field.TypeTime, Nullable: true, Comment: "登录时间"},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Comment: "浏览器的用户代理信息"},
		{Name: "browser_name", Type: field.TypeString, Nullable: true, Comment: "浏览器名称"},
		{Name: "browser_version", Type: field.TypeString, Nullable: true, Comment: "浏览器版本"},
		{Name: "client_id", Type: field.TypeString, Nullable: true, Comment: "客户端ID"},
		{Name: "client_name", Type: field.TypeString, Nullable: true, Comment: "客户端名称"},
		{Name: "os_name", Type: field.TypeString, Nullable: true, Comment: "操作系统名称"},
		{Name: "os_version", Type: field.TypeString, Nullable: true, Comment: "操作系统版本"},
		{Name: "user_id", Type: field.TypeUint32, Nullable: true, Comment: "操作者用户ID"},
		{Name: "username", Type: field.TypeString, Nullable: true, Comment: "操作者账号名"},
		{Name: "status_code", Type: field.TypeInt32, Nullable: true, Comment: "状态码"},
		{Name: "success", Type: field.TypeBool, Nullable: true, Comment: "操作成功"},
		{Name: "reason", Type: field.TypeString, Nullable: true, Comment: "登录失败原因"},
		{Name: "location", Type: field.TypeString, Nullable: true, Comment: "登录地理位置"},
	}
	// SysAdminLoginLogsTable holds the schema information for the "sys_admin_login_logs" table.
	SysAdminLoginLogsTable = &schema.Table{
		Name:       "sys_admin_login_logs",
		Comment:    "后台登录日志表",
		Columns:    SysAdminLoginLogsColumns,
		PrimaryKey: []*schema.Column{SysAdminLoginLogsColumns[0]},
	}
	// SysAdminLoginRestrictionsColumns holds the columns for the "sys_admin_login_restrictions" table.
	SysAdminLoginRestrictionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "target_id", Type: field.TypeUint32, Nullable: true, Comment: "目标用户ID"},
		{Name: "value", Type: field.TypeString, Nullable: true, Comment: "限制值（如IP地址、MAC地址或地区代码）"},
		{Name: "reason", Type: field.TypeString, Nullable: true, Comment: "限制原因"},
		{Name: "type", Type: field.TypeEnum, Nullable: true, Comment: "限制类型", Enums: []string{"BLACK_LIST", "WHITE_LIST"}, Default: "BLACK_LIST"},
		{Name: "method", Type: field.TypeEnum, Nullable: true, Comment: "限制方式", Enums: []string{"IP", "MAC", "REGION", "TIME", "DEVICE"}, Default: "IP"},
	}
	// SysAdminLoginRestrictionsTable holds the schema information for the "sys_admin_login_restrictions" table.
	SysAdminLoginRestrictionsTable = &schema.Table{
		Name:       "sys_admin_login_restrictions",
		Comment:    "后台登录限制表",
		Columns:    SysAdminLoginRestrictionsColumns,
		PrimaryKey: []*schema.Column{SysAdminLoginRestrictionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_sys_admin_login_restriction_target_type_method",
				Unique:  true,
				Columns: []*schema.Column{SysAdminLoginRestrictionsColumns[7], SysAdminLoginRestrictionsColumns[10], SysAdminLoginRestrictionsColumns[11]},
			},
		},
	}
	// SysAdminOperationLogsColumns holds the columns for the "sys_admin_operation_logs" table.
	SysAdminOperationLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "request_id", Type: field.TypeString, Nullable: true, Comment: "请求ID"},
		{Name: "method", Type: field.TypeString, Nullable: true, Comment: "请求方法"},
		{Name: "operation", Type: field.TypeString, Nullable: true, Comment: "操作方法"},
		{Name: "path", Type: field.TypeString, Nullable: true, Comment: "请求路径"},
		{Name: "referer", Type: field.TypeString, Nullable: true, Comment: "请求源"},
		{Name: "request_uri", Type: field.TypeString, Nullable: true, Comment: "请求URI"},
		{Name: "request_body", Type: field.TypeString, Nullable: true, Comment: "请求体"},
		{Name: "request_header", Type: field.TypeString, Nullable: true, Comment: "请求头"},
		{Name: "response", Type: field.TypeString, Nullable: true, Comment: "响应信息"},
		{Name: "cost_time", Type: field.TypeFloat64, Nullable: true, Comment: "操作耗时"},
		{Name: "user_id", Type: field.TypeUint32, Nullable: true, Comment: "操作者用户ID"},
		{Name: "username", Type: field.TypeString, Nullable: true, Comment: "操作者账号名"},
		{Name: "client_ip", Type: field.TypeString, Nullable: true, Comment: "操作者IP"},
		{Name: "status_code", Type: field.TypeInt32, Nullable: true, Comment: "状态码"},
		{Name: "reason", Type: field.TypeString, Nullable: true, Comment: "操作失败原因"},
		{Name: "success", Type: field.TypeBool, Nullable: true, Comment: "操作成功"},
		{Name: "location", Type: field.TypeString, Nullable: true, Comment: "操作地理位置"},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Comment: "浏览器的用户代理信息"},
		{Name: "browser_name", Type: field.TypeString, Nullable: true, Comment: "浏览器名称"},
		{Name: "browser_version", Type: field.TypeString, Nullable: true, Comment: "浏览器版本"},
		{Name: "client_id", Type: field.TypeString, Nullable: true, Comment: "客户端ID"},
		{Name: "client_name", Type: field.TypeString, Nullable: true, Comment: "客户端名称"},
		{Name: "os_name", Type: field.TypeString, Nullable: true, Comment: "操作系统名称"},
		{Name: "os_version", Type: field.TypeString, Nullable: true, Comment: "操作系统版本"},
	}
	// SysAdminOperationLogsTable holds the schema information for the "sys_admin_operation_logs" table.
	SysAdminOperationLogsTable = &schema.Table{
		Name:       "sys_admin_operation_logs",
		Comment:    "后台操作日志表",
		Columns:    SysAdminOperationLogsColumns,
		PrimaryKey: []*schema.Column{SysAdminOperationLogsColumns[0]},
	}
	// SysAPIResourcesColumns holds the columns for the "sys_api_resources" table.
	SysAPIResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "描述"},
		{Name: "module", Type: field.TypeString, Nullable: true, Comment: "所属业务模块"},
		{Name: "module_description", Type: field.TypeString, Nullable: true, Comment: "业务模块描述"},
		{Name: "operation", Type: field.TypeString, Nullable: true, Comment: "接口操作名"},
		{Name: "path", Type: field.TypeString, Nullable: true, Comment: "接口路径"},
		{Name: "method", Type: field.TypeString, Nullable: true, Comment: "请求方法"},
		{Name: "scope", Type: field.TypeEnum, Nullable: true, Comment: "作用域", Enums: []string{"ADMIN", "APP"}, Default: "ADMIN"},
	}
	// SysAPIResourcesTable holds the schema information for the "sys_api_resources" table.
	SysAPIResourcesTable = &schema.Table{
		Name:       "sys_api_resources",
		Comment:    "API资源表",
		Columns:    SysAPIResourcesColumns,
		PrimaryKey: []*schema.Column{SysAPIResourcesColumns[0]},
	}
	// SysDictEntriesColumns holds the columns for the "sys_dict_entries" table.
	SysDictEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "描述"},
		{Name: "sort_order", Type: field.TypeInt32, Nullable: true, Comment: "排序顺序，值越小越靠前", Default: 0},
		{Name: "is_enabled", Type: field.TypeBool, Nullable: true, Comment: "是否启用", Default: true},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "entry_label", Type: field.TypeString, Nullable: true, Comment: "字典项的显示标签"},
		{Name: "entry_value", Type: field.TypeString, Nullable: true, Comment: "字典项的实际值"},
		{Name: "numeric_value", Type: field.TypeInt32, Nullable: true, Comment: "数值型值"},
		{Name: "language_code", Type: field.TypeString, Nullable: true, Comment: "语言代码"},
		{Name: "type_id", Type: field.TypeUint32},
	}
	// SysDictEntriesTable holds the schema information for the "sys_dict_entries" table.
	SysDictEntriesTable = &schema.Table{
		Name:       "sys_dict_entries",
		Comment:    "字典条目表",
		Columns:    SysDictEntriesColumns,
		PrimaryKey: []*schema.Column{SysDictEntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_dict_entries_sys_dict_types_sys_dict_types",
				Columns:    []*schema.Column{SysDictEntriesColumns[15]},
				RefColumns: []*schema.Column{SysDictTypesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "dictentry_is_enabled",
				Unique:  false,
				Columns: []*schema.Column{SysDictEntriesColumns[9]},
			},
			{
				Name:    "dictentry_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysDictEntriesColumns[10]},
			},
			{
				Name:    "uk_sys_dict_entries_entry_value",
				Unique:  true,
				Columns: []*schema.Column{SysDictEntriesColumns[12], SysDictEntriesColumns[15]},
			},
		},
	}
	// SysDictTypesColumns holds the columns for the "sys_dict_types" table.
	SysDictTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "is_enabled", Type: field.TypeBool, Nullable: true, Comment: "是否启用", Default: true},
		{Name: "sort_order", Type: field.TypeInt32, Nullable: true, Comment: "排序顺序，值越小越靠前", Default: 0},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "描述"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "type_code", Type: field.TypeString, Nullable: true, Comment: "字典类型唯一代码"},
		{Name: "type_name", Type: field.TypeString, Nullable: true, Comment: "字典类型名称"},
	}
	// SysDictTypesTable holds the schema information for the "sys_dict_types" table.
	SysDictTypesTable = &schema.Table{
		Name:       "sys_dict_types",
		Comment:    "字典类型表",
		Columns:    SysDictTypesColumns,
		PrimaryKey: []*schema.Column{SysDictTypesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "dicttype_is_enabled",
				Unique:  false,
				Columns: []*schema.Column{SysDictTypesColumns[7]},
			},
			{
				Name:    "dicttype_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysDictTypesColumns[10]},
			},
			{
				Name:    "idx_sys_dict_types_type_code",
				Unique:  true,
				Columns: []*schema.Column{SysDictTypesColumns[11]},
			},
		},
	}
	// FilesColumns holds the columns for the "files" table.
	FilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "provider", Type: field.TypeEnum, Nullable: true, Comment: "OSS供应商", Enums: []string{"UNKNOWN", "MINIO", "ALIYUN", "QINIU", "TENCENT", "AWS", "GOOGLE", "AZURE", "BAIDU", "HUAWEI", "QCLOUD", "LOCAL"}, Default: "MINIO"},
		{Name: "bucket_name", Type: field.TypeString, Nullable: true, Comment: "存储桶名称"},
		{Name: "file_directory", Type: field.TypeString, Nullable: true, Comment: "文件目录"},
		{Name: "file_guid", Type: field.TypeString, Nullable: true, Comment: "文件Guid"},
		{Name: "save_file_name", Type: field.TypeString, Nullable: true, Comment: "保存文件名"},
		{Name: "file_name", Type: field.TypeString, Nullable: true, Comment: "文件名"},
		{Name: "extension", Type: field.TypeString, Nullable: true, Comment: "文件扩展名"},
		{Name: "size", Type: field.TypeUint64, Nullable: true, Comment: "文件字节长度"},
		{Name: "size_format", Type: field.TypeString, Nullable: true, Comment: "文件大小格式化"},
		{Name: "link_url", Type: field.TypeString, Nullable: true, Comment: "链接地址"},
		{Name: "md5", Type: field.TypeString, Nullable: true, Comment: "md5码，防止上传重复文件"},
	}
	// FilesTable holds the schema information for the "files" table.
	FilesTable = &schema.Table{
		Name:       "files",
		Comment:    "文件表",
		Columns:    FilesColumns,
		PrimaryKey: []*schema.Column{FilesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "file_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[8]},
			},
		},
	}
	// InternalMessagesColumns holds the columns for the "internal_messages" table.
	InternalMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "title", Type: field.TypeString, Nullable: true, Comment: "消息标题"},
		{Name: "content", Type: field.TypeString, Nullable: true, Comment: "消息内容"},
		{Name: "sender_id", Type: field.TypeUint32, Nullable: true, Comment: "发送者用户ID"},
		{Name: "category_id", Type: field.TypeUint32, Nullable: true, Comment: "分类ID"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "消息状态", Enums: []string{"DRAFT", "PUBLISHED", "SCHEDULED", "REVOKED", "ARCHIVED", "DELETED"}, Default: "DRAFT"},
		{Name: "type", Type: field.TypeEnum, Nullable: true, Comment: "消息类型", Enums: []string{"NOTIFICATION", "PRIVATE", "GROUP"}, Default: "NOTIFICATION"},
	}
	// InternalMessagesTable holds the schema information for the "internal_messages" table.
	InternalMessagesTable = &schema.Table{
		Name:       "internal_messages",
		Comment:    "站内信消息表",
		Columns:    InternalMessagesColumns,
		PrimaryKey: []*schema.Column{InternalMessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "internalmessage_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{InternalMessagesColumns[7]},
			},
		},
	}
	// InternalMessageCategoriesColumns holds the columns for the "internal_message_categories" table.
	InternalMessageCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "is_enabled", Type: field.TypeBool, Nullable: true, Comment: "是否启用", Default: true},
		{Name: "sort_order", Type: field.TypeInt32, Nullable: true, Comment: "排序顺序，值越小越靠前", Default: 0},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "name", Type: field.TypeString, Nullable: true, Comment: "名称"},
		{Name: "code", Type: field.TypeString, Nullable: true, Comment: "编码"},
		{Name: "icon_url", Type: field.TypeString, Nullable: true, Comment: "图标URL"},
		{Name: "parent_id", Type: field.TypeUint32, Nullable: true, Comment: "父节点ID"},
	}
	// InternalMessageCategoriesTable holds the schema information for the "internal_message_categories" table.
	InternalMessageCategoriesTable = &schema.Table{
		Name:       "internal_message_categories",
		Comment:    "站内信消息分类表",
		Columns:    InternalMessageCategoriesColumns,
		PrimaryKey: []*schema.Column{InternalMessageCategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "internal_message_categories_internal_message_categories_children",
				Columns:    []*schema.Column{InternalMessageCategoriesColumns[14]},
				RefColumns: []*schema.Column{InternalMessageCategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "internalmessagecategory_is_enabled",
				Unique:  false,
				Columns: []*schema.Column{InternalMessageCategoriesColumns[7]},
			},
			{
				Name:    "internalmessagecategory_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{InternalMessageCategoriesColumns[10]},
			},
			{
				Name:    "idx_internal_message_category_code",
				Unique:  true,
				Columns: []*schema.Column{InternalMessageCategoriesColumns[12]},
			},
			{
				Name:    "idx_internal_message_category_name",
				Unique:  false,
				Columns: []*schema.Column{InternalMessageCategoriesColumns[11]},
			},
		},
	}
	// InternalMessageRecipientsColumns holds the columns for the "internal_message_recipients" table.
	InternalMessageRecipientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "message_id", Type: field.TypeUint32, Nullable: true, Comment: "站内信内容ID"},
		{Name: "recipient_user_id", Type: field.TypeUint32, Nullable: true, Comment: "接收者用户ID"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "消息状态", Enums: []string{"SENT", "RECEIVED", "READ", "REVOKED", "DELETED"}},
		{Name: "received_at", Type: field.TypeTime, Nullable: true, Comment: "消息到达用户收件箱的时间"},
		{Name: "read_at", Type: field.TypeTime, Nullable: true, Comment: "用户阅读消息的时间"},
	}
	// InternalMessageRecipientsTable holds the schema information for the "internal_message_recipients" table.
	InternalMessageRecipientsTable = &schema.Table{
		Name:       "internal_message_recipients",
		Comment:    "站内信消息用户接收信息表",
		Columns:    InternalMessageRecipientsColumns,
		PrimaryKey: []*schema.Column{InternalMessageRecipientsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "internalmessagerecipient_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{InternalMessageRecipientsColumns[4]},
			},
		},
	}
	// SysLanguagesColumns holds the columns for the "sys_languages" table.
	SysLanguagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "sort_order", Type: field.TypeInt32, Nullable: true, Comment: "排序顺序，值越小越靠前", Default: 0},
		{Name: "is_enabled", Type: field.TypeBool, Nullable: true, Comment: "是否启用", Default: true},
		{Name: "language_code", Type: field.TypeString, Nullable: true, Comment: "标准语言代码"},
		{Name: "language_name", Type: field.TypeString, Nullable: true, Comment: "语言名称"},
		{Name: "native_name", Type: field.TypeString, Nullable: true, Comment: "本地语言名称"},
		{Name: "is_default", Type: field.TypeBool, Nullable: true, Comment: "是否为默认语言", Default: false},
	}
	// SysLanguagesTable holds the schema information for the "sys_languages" table.
	SysLanguagesTable = &schema.Table{
		Name:       "sys_languages",
		Comment:    "语言表",
		Columns:    SysLanguagesColumns,
		PrimaryKey: []*schema.Column{SysLanguagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "language_is_enabled",
				Unique:  false,
				Columns: []*schema.Column{SysLanguagesColumns[8]},
			},
		},
	}
	// SysMembershipsColumns holds the columns for the "sys_memberships" table.
	SysMembershipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "user_id", Type: field.TypeUint32, Comment: "用户ID"},
		{Name: "org_unit_id", Type: field.TypeUint32, Nullable: true, Comment: "组织架构ID（单一，冗余/互斥）"},
		{Name: "position_id", Type: field.TypeUint32, Nullable: true, Comment: "职位ID（单一，冗余/互斥）"},
		{Name: "role_id", Type: field.TypeUint32, Nullable: true, Comment: "角色ID（单一，冗余/互斥）"},
		{Name: "is_primary", Type: field.TypeBool, Comment: "是否主身份", Default: false},
		{Name: "start_at", Type: field.TypeTime, Nullable: true, Comment: "生效时间"},
		{Name: "end_at", Type: field.TypeTime, Nullable: true, Comment: "失效时间"},
		{Name: "assigned_at", Type: field.TypeTime, Nullable: true, Comment: "分配时间（UTC）"},
		{Name: "assigned_by", Type: field.TypeUint32, Nullable: true, Comment: "分配者用户ID"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "状态", Enums: []string{"ACTIVE", "PENDING", "INACTIVE", "SUSPENDED", "EXPIRED"}, Default: "ACTIVE"},
	}
	// SysMembershipsTable holds the schema information for the "sys_memberships" table.
	SysMembershipsTable = &schema.Table{
		Name:       "sys_memberships",
		Comment:    "成员关联表。存储用户在不同租户或系统空间的身份、状态及角色。tenant_id 为 NULL 时代表全局或个人系统成员。",
		Columns:    SysMembershipsColumns,
		PrimaryKey: []*schema.Column{SysMembershipsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "membership_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipsColumns[7]},
			},
			{
				Name:    "uix_sys_membership_tenant_user",
				Unique:  true,
				Columns: []*schema.Column{SysMembershipsColumns[7], SysMembershipsColumns[9]},
			},
			{
				Name:    "idx_membership_user_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipsColumns[9]},
			},
			{
				Name:    "idx_membership_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipsColumns[7]},
			},
			{
				Name:    "idx_membership_org_unit_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipsColumns[10]},
			},
			{
				Name:    "idx_membership_position_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipsColumns[11]},
			},
			{
				Name:    "idx_membership_role_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipsColumns[12]},
			},
		},
	}
	// SysMembershipOrgUnitsColumns holds the columns for the "sys_membership_org_units" table.
	SysMembershipOrgUnitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "membership_id", Type: field.TypeUint32, Comment: "membership ID"},
		{Name: "org_unit_id", Type: field.TypeUint32, Comment: "组织单元 ID"},
		{Name: "position_id", Type: field.TypeUint32, Nullable: true, Comment: "岗位 ID（可选，冗余）"},
		{Name: "role_id", Type: field.TypeUint32, Nullable: true, Comment: "角色 ID（可选，冗余）"},
		{Name: "start_at", Type: field.TypeTime, Nullable: true, Comment: "生效时间（UTC）"},
		{Name: "end_at", Type: field.TypeTime, Nullable: true, Comment: "结束时间（UTC）"},
		{Name: "assigned_at", Type: field.TypeTime, Nullable: true, Comment: "分配时间（UTC）"},
		{Name: "assigned_by", Type: field.TypeUint32, Nullable: true, Comment: "分配者用户 ID"},
		{Name: "is_primary", Type: field.TypeBool, Comment: "是否为主所属", Default: false},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "关联状态", Enums: []string{"ACTIVE", "PENDING", "INACTIVE", "SUSPENDED", "EXPIRED"}, Default: "ACTIVE"},
	}
	// SysMembershipOrgUnitsTable holds the schema information for the "sys_membership_org_units" table.
	SysMembershipOrgUnitsTable = &schema.Table{
		Name:       "sys_membership_org_units",
		Comment:    "成员与组织单元关联表",
		Columns:    SysMembershipOrgUnitsColumns,
		PrimaryKey: []*schema.Column{SysMembershipOrgUnitsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "membershiporgunit_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipOrgUnitsColumns[7]},
			},
			{
				Name:    "uix_membership_org_unit_tenant_mem_org",
				Unique:  true,
				Columns: []*schema.Column{SysMembershipOrgUnitsColumns[7], SysMembershipOrgUnitsColumns[9], SysMembershipOrgUnitsColumns[10]},
			},
			{
				Name:    "idx_mou_membership_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipOrgUnitsColumns[9]},
			},
			{
				Name:    "idx_mou_org_unit_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipOrgUnitsColumns[10]},
			},
		},
	}
	// SysMembershipPositionsColumns holds the columns for the "sys_membership_positions" table.
	SysMembershipPositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "membership_id", Type: field.TypeUint32, Comment: "membership ID"},
		{Name: "position_id", Type: field.TypeUint32, Comment: "岗位ID"},
		{Name: "is_primary", Type: field.TypeBool, Nullable: true, Comment: "是否主岗位", Default: false},
		{Name: "start_at", Type: field.TypeTime, Nullable: true, Comment: "生效时间"},
		{Name: "end_at", Type: field.TypeTime, Nullable: true, Comment: "失效时间"},
		{Name: "assigned_at", Type: field.TypeTime, Nullable: true, Comment: "岗位分配时间"},
		{Name: "assigned_by", Type: field.TypeUint32, Nullable: true, Comment: "分配者用户 ID"},
		{Name: "status", Type: field.TypeEnum, Comment: "岗位状态", Enums: []string{"PROBATION", "ACTIVE", "LEAVE", "TERMINATED", "EXPIRED"}, Default: "ACTIVE"},
	}
	// SysMembershipPositionsTable holds the schema information for the "sys_membership_positions" table.
	SysMembershipPositionsTable = &schema.Table{
		Name:       "sys_membership_positions",
		Comment:    "用户与岗位关联表",
		Columns:    SysMembershipPositionsColumns,
		PrimaryKey: []*schema.Column{SysMembershipPositionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "membershipposition_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipPositionsColumns[7]},
			},
			{
				Name:    "uix_sys_membership_position_tenant_mem_pos",
				Unique:  true,
				Columns: []*schema.Column{SysMembershipPositionsColumns[7], SysMembershipPositionsColumns[9], SysMembershipPositionsColumns[10]},
			},
			{
				Name:    "idx_sys_membership_position_membership_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipPositionsColumns[9]},
			},
			{
				Name:    "idx_sys_membership_position_position_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipPositionsColumns[10]},
			},
		},
	}
	// SysMembershipRolesColumns holds the columns for the "sys_membership_roles" table.
	SysMembershipRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "membership_id", Type: field.TypeUint32, Comment: "membership ID"},
		{Name: "role_id", Type: field.TypeUint32, Comment: "角色ID"},
		{Name: "start_at", Type: field.TypeTime, Nullable: true, Comment: "生效时间（UTC）"},
		{Name: "end_at", Type: field.TypeTime, Nullable: true, Comment: "失效时间（UTC）"},
		{Name: "assigned_at", Type: field.TypeTime, Nullable: true, Comment: "分配时间（UTC）"},
		{Name: "assigned_by", Type: field.TypeUint32, Nullable: true, Comment: "分配者用户ID"},
		{Name: "is_primary", Type: field.TypeBool, Comment: "是否为主角色", Default: false},
		{Name: "status", Type: field.TypeEnum, Comment: "岗位状态", Enums: []string{"PENDING", "ACTIVE", "DISABLED", "EXPIRED"}, Default: "ACTIVE"},
	}
	// SysMembershipRolesTable holds the schema information for the "sys_membership_roles" table.
	SysMembershipRolesTable = &schema.Table{
		Name:       "sys_membership_roles",
		Comment:    "成员-角色 关联表（支持多角色及分配属性）",
		Columns:    SysMembershipRolesColumns,
		PrimaryKey: []*schema.Column{SysMembershipRolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "membershiprole_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipRolesColumns[7]},
			},
			{
				Name:    "uix_mem_role_tenant_memid_role",
				Unique:  true,
				Columns: []*schema.Column{SysMembershipRolesColumns[7], SysMembershipRolesColumns[8], SysMembershipRolesColumns[9]},
			},
			{
				Name:    "idx_mem_role_role_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipRolesColumns[9]},
			},
			{
				Name:    "idx_mem_role_membership_id",
				Unique:  false,
				Columns: []*schema.Column{SysMembershipRolesColumns[8]},
			},
		},
	}
	// SysMenusColumns holds the columns for the "sys_menus" table.
	SysMenusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "菜单状态", Enums: []string{"ON", "OFF"}, Default: "ON"},
		{Name: "type", Type: field.TypeEnum, Nullable: true, Comment: "菜单类型 CATALOG: 目录 MENU: 菜单 BUTTON: 按钮 EMBEDDED: 内嵌 LINK: 外链", Enums: []string{"CATALOG", "MENU", "BUTTON", "EMBEDDED", "LINK"}, Default: "MENU"},
		{Name: "path", Type: field.TypeString, Nullable: true, Comment: "路径,当其类型为'按钮'的时候对应的数据操作名,例如:/user.service.v1.UserService/Login", Default: ""},
		{Name: "redirect", Type: field.TypeString, Nullable: true, Comment: "重定向地址"},
		{Name: "alias", Type: field.TypeString, Nullable: true, Comment: "路由别名"},
		{Name: "name", Type: field.TypeString, Nullable: true, Comment: "路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。"},
		{Name: "component", Type: field.TypeString, Nullable: true, Comment: "前端页面组件", Default: ""},
		{Name: "meta", Type: field.TypeJSON, Nullable: true, Comment: "前端页面组件"},
		{Name: "parent_id", Type: field.TypeUint32, Nullable: true, Comment: "父节点ID"},
	}
	// SysMenusTable holds the schema information for the "sys_menus" table.
	SysMenusTable = &schema.Table{
		Name:       "sys_menus",
		Comment:    "后台目录表",
		Columns:    SysMenusColumns,
		PrimaryKey: []*schema.Column{SysMenusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_menus_sys_menus_children",
				Columns:    []*schema.Column{SysMenusColumns[16]},
				RefColumns: []*schema.Column{SysMenusColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SysOrgUnitsColumns holds the columns for the "sys_org_units" table.
	SysOrgUnitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "状态", Enums: []string{"OFF", "ON"}, Default: "ON"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "描述"},
		{Name: "name", Type: field.TypeString, Comment: "名称"},
		{Name: "code", Type: field.TypeString, Nullable: true, Comment: "唯一编码（可用于导入/识别）"},
		{Name: "path", Type: field.TypeString, Nullable: true, Comment: "树路径，如：/1/10/"},
		{Name: "sort_order", Type: field.TypeInt32, Nullable: true, Comment: "排序序号", Default: 0},
		{Name: "leader_id", Type: field.TypeUint32, Nullable: true, Comment: "负责人用户ID"},
		{Name: "type", Type: field.TypeEnum, Comment: "组织类型", Enums: []string{"COMPANY", "DIVISION", "DEPARTMENT", "TEAM", "PROJECT", "COMMITTEE", "REGION", "OTHER"}, Default: "DEPARTMENT"},
		{Name: "business_scopes", Type: field.TypeJSON, Nullable: true, Comment: "组织的业务范围/服务条线"},
		{Name: "external_id", Type: field.TypeString, Nullable: true, Comment: "外部系统ID"},
		{Name: "is_legal_entity", Type: field.TypeBool, Nullable: true, Comment: "是否为法定主体", Default: false},
		{Name: "registration_number", Type: field.TypeString, Nullable: true, Comment: "注册号/统一社会信用代码"},
		{Name: "tax_id", Type: field.TypeString, Nullable: true, Comment: "税号"},
		{Name: "legal_entity_org_id", Type: field.TypeUint32, Nullable: true, Comment: "关联的法定主体组织ID"},
		{Name: "address", Type: field.TypeString, Nullable: true, Comment: "详细地址"},
		{Name: "phone", Type: field.TypeString, Nullable: true, Comment: "联系电话"},
		{Name: "email", Type: field.TypeString, Nullable: true, Comment: "联系邮箱"},
		{Name: "timezone", Type: field.TypeString, Nullable: true, Comment: "时区"},
		{Name: "country", Type: field.TypeString, Nullable: true, Comment: "国家/地区代码"},
		{Name: "latitude", Type: field.TypeFloat64, Nullable: true, Comment: "纬度"},
		{Name: "longitude", Type: field.TypeFloat64, Nullable: true, Comment: "经度"},
		{Name: "start_at", Type: field.TypeTime, Nullable: true, Comment: "生效时间（UTC）"},
		{Name: "end_at", Type: field.TypeTime, Nullable: true, Comment: "结束有效期（UTC）"},
		{Name: "contact_user_id", Type: field.TypeUint32, Nullable: true, Comment: "业务联系人用户ID"},
		{Name: "permission_tags", Type: field.TypeJSON, Nullable: true, Comment: "与权限/角色映射的标签"},
		{Name: "parent_id", Type: field.TypeUint32, Nullable: true, Comment: "父节点ID"},
	}
	// SysOrgUnitsTable holds the schema information for the "sys_org_units" table.
	SysOrgUnitsTable = &schema.Table{
		Name:       "sys_org_units",
		Comment:    "组织单元表",
		Columns:    SysOrgUnitsColumns,
		PrimaryKey: []*schema.Column{SysOrgUnitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_org_units_sys_org_units_children",
				Columns:    []*schema.Column{SysOrgUnitsColumns[34]},
				RefColumns: []*schema.Column{SysOrgUnitsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "orgunit_status",
				Unique:  false,
				Columns: []*schema.Column{SysOrgUnitsColumns[7]},
			},
			{
				Name:    "orgunit_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysOrgUnitsColumns[8]},
			},
			{
				Name:    "idx_org_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysOrgUnitsColumns[8]},
			},
			{
				Name:    "uix_org_tenant_code",
				Unique:  true,
				Columns: []*schema.Column{SysOrgUnitsColumns[8], SysOrgUnitsColumns[12]},
			},
		},
	}
	// SysPermissionsColumns holds the columns for the "sys_permissions" table.
	SysPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "状态", Enums: []string{"OFF", "ON"}, Default: "ON"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "name", Type: field.TypeString, Comment: "权限名称（如：删除用户）"},
		{Name: "code", Type: field.TypeString, Nullable: true, Comment: "权限唯一编码（如：user.delete）"},
		{Name: "path", Type: field.TypeString, Nullable: true, Comment: "树路径，如：/1/10/"},
		{Name: "module", Type: field.TypeString, Nullable: true, Comment: "所属业务模块（如：用户管理/订单管理）"},
		{Name: "sort_order", Type: field.TypeInt32, Nullable: true, Comment: "排序序号", Default: 0},
		{Name: "type", Type: field.TypeEnum, Comment: "权限类型", Enums: []string{"CATALOG", "MENU", "PAGE", "BUTTON", "API", "DATA", "OTHER"}, Default: "API"},
		{Name: "parent_id", Type: field.TypeUint32, Nullable: true, Comment: "父节点ID"},
	}
	// SysPermissionsTable holds the schema information for the "sys_permissions" table.
	SysPermissionsTable = &schema.Table{
		Name:       "sys_permissions",
		Comment:    "权限核心表",
		Columns:    SysPermissionsColumns,
		PrimaryKey: []*schema.Column{SysPermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_permissions_sys_permissions_children",
				Columns:    []*schema.Column{SysPermissionsColumns[16]},
				RefColumns: []*schema.Column{SysPermissionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "permission_status",
				Unique:  false,
				Columns: []*schema.Column{SysPermissionsColumns[8]},
			},
			{
				Name:    "permission_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysPermissionsColumns[9]},
			},
			{
				Name:    "idx_perm_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysPermissionsColumns[9]},
			},
			{
				Name:    "idx_perm_parent_id",
				Unique:  false,
				Columns: []*schema.Column{SysPermissionsColumns[16]},
			},
			{
				Name:    "uix_perm_tenant_code",
				Unique:  true,
				Columns: []*schema.Column{SysPermissionsColumns[9], SysPermissionsColumns[11]},
			},
			{
				Name:    "idx_perm_module_type",
				Unique:  false,
				Columns: []*schema.Column{SysPermissionsColumns[13], SysPermissionsColumns[15]},
			},
		},
	}
	// SysPermissionAPIResourcesColumns holds the columns for the "sys_permission_api_resources" table.
	SysPermissionAPIResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "api_resource_id", Type: field.TypeUint32, Comment: "API资源ID（关联sys_api_resources.id）"},
		{Name: "permission_id", Type: field.TypeUint32, Comment: "权限ID（关联sys_permissions.id）"},
	}
	// SysPermissionAPIResourcesTable holds the schema information for the "sys_permission_api_resources" table.
	SysPermissionAPIResourcesTable = &schema.Table{
		Name:       "sys_permission_api_resources",
		Comment:    "权限点 - API接口多对多关联表",
		Columns:    SysPermissionAPIResourcesColumns,
		PrimaryKey: []*schema.Column{SysPermissionAPIResourcesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permissionapiresource_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysPermissionAPIResourcesColumns[7]},
			},
			{
				Name:    "uk_perm_api",
				Unique:  true,
				Columns: []*schema.Column{SysPermissionAPIResourcesColumns[8], SysPermissionAPIResourcesColumns[9]},
			},
			{
				Name:    "uix_perm_api_tenant",
				Unique:  true,
				Columns: []*schema.Column{SysPermissionAPIResourcesColumns[7], SysPermissionAPIResourcesColumns[8]},
			},
		},
	}
	// SysPermissionMenusColumns holds the columns for the "sys_permission_menus" table.
	SysPermissionMenusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "menu_id", Type: field.TypeUint32, Comment: "菜单ID（关联sys_menus.id）"},
		{Name: "permission_id", Type: field.TypeUint32, Comment: "权限ID（关联sys_permissions.id）"},
	}
	// SysPermissionMenusTable holds the schema information for the "sys_permission_menus" table.
	SysPermissionMenusTable = &schema.Table{
		Name:       "sys_permission_menus",
		Comment:    "权限点 - 前端菜单多对多关联表",
		Columns:    SysPermissionMenusColumns,
		PrimaryKey: []*schema.Column{SysPermissionMenusColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permissionmenu_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysPermissionMenusColumns[7]},
			},
			{
				Name:    "uk_perm_menu",
				Unique:  true,
				Columns: []*schema.Column{SysPermissionMenusColumns[8], SysPermissionMenusColumns[9]},
			},
			{
				Name:    "uix_perm_menu_tenant",
				Unique:  true,
				Columns: []*schema.Column{SysPermissionMenusColumns[7], SysPermissionMenusColumns[8]},
			},
		},
	}
	// SysPositionsColumns holds the columns for the "sys_positions" table.
	SysPositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "sort_order", Type: field.TypeInt32, Nullable: true, Comment: "排序顺序，值越小越靠前", Default: 0},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "状态", Enums: []string{"OFF", "ON"}, Default: "ON"},
		{Name: "name", Type: field.TypeString, Nullable: true, Comment: "职位名称"},
		{Name: "code", Type: field.TypeString, Nullable: true, Comment: "唯一编码"},
		{Name: "org_unit_id", Type: field.TypeUint32, Comment: "所属组织单元ID"},
		{Name: "reports_to_position_id", Type: field.TypeUint32, Nullable: true, Comment: "汇报关系"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "职位描述"},
		{Name: "job_family", Type: field.TypeString, Nullable: true, Comment: "职类/序列"},
		{Name: "job_grade", Type: field.TypeString, Nullable: true, Comment: "职级"},
		{Name: "level", Type: field.TypeInt32, Nullable: true, Comment: "数值化职级"},
		{Name: "headcount", Type: field.TypeUint32, Nullable: true, Comment: "编制人数", Default: 0},
		{Name: "is_key_position", Type: field.TypeBool, Nullable: true, Comment: "是否关键岗位", Default: false},
		{Name: "type", Type: field.TypeEnum, Comment: "岗位类型", Enums: []string{"REGULAR", "MANAGER", "LEAD", "INTERN", "CONTRACT", "OTHER"}, Default: "REGULAR"},
		{Name: "start_at", Type: field.TypeTime, Nullable: true, Comment: "生效时间（UTC）"},
		{Name: "end_at", Type: field.TypeTime, Nullable: true, Comment: "结束有效期（UTC）"},
		{Name: "parent_id", Type: field.TypeUint32, Nullable: true, Comment: "父节点ID"},
	}
	// SysPositionsTable holds the schema information for the "sys_positions" table.
	SysPositionsTable = &schema.Table{
		Name:       "sys_positions",
		Comment:    "职位表",
		Columns:    SysPositionsColumns,
		PrimaryKey: []*schema.Column{SysPositionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_positions_sys_positions_children",
				Columns:    []*schema.Column{SysPositionsColumns[24]},
				RefColumns: []*schema.Column{SysPositionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "position_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysPositionsColumns[9]},
			},
			{
				Name:    "position_status",
				Unique:  false,
				Columns: []*schema.Column{SysPositionsColumns[10]},
			},
			{
				Name:    "idx_sys_position_code",
				Unique:  true,
				Columns: []*schema.Column{SysPositionsColumns[12]},
			},
			{
				Name:    "uix_sys_position_tenant_code",
				Unique:  true,
				Columns: []*schema.Column{SysPositionsColumns[9], SysPositionsColumns[12]},
			},
			{
				Name:    "idx_sys_position_name",
				Unique:  false,
				Columns: []*schema.Column{SysPositionsColumns[11]},
			},
			{
				Name:    "idx_sys_position_org_unit_id",
				Unique:  false,
				Columns: []*schema.Column{SysPositionsColumns[13]},
			},
			{
				Name:    "idx_sys_position_type",
				Unique:  false,
				Columns: []*schema.Column{SysPositionsColumns[21]},
			},
		},
	}
	// SysRolesColumns holds the columns for the "sys_roles" table.
	SysRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "sort_order", Type: field.TypeInt32, Nullable: true, Comment: "排序顺序，值越小越靠前", Default: 0},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "name", Type: field.TypeString, Nullable: true, Comment: "角色名称"},
		{Name: "code", Type: field.TypeString, Nullable: true, Comment: "角色标识"},
		{Name: "custom_org_unit_ids", Type: field.TypeJSON, Nullable: true, Comment: "当 DataScope 为 SELECTED_UNITS 时关联的组织单元列表"},
		{Name: "data_scope", Type: field.TypeEnum, Nullable: true, Comment: "数据权限范围", Enums: []string{"ALL", "SELF", "UNIT_ONLY", "UNIT_AND_CHILD", "SELECTED_UNITS"}},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "角色状态", Enums: []string{"ON", "OFF"}, Default: "ON"},
		{Name: "type", Type: field.TypeEnum, Nullable: true, Comment: "角色类型", Enums: []string{"SYSTEM", "CUSTOM"}, Default: "SYSTEM"},
		{Name: "parent_id", Type: field.TypeUint32, Nullable: true, Comment: "父节点ID"},
	}
	// SysRolesTable holds the schema information for the "sys_roles" table.
	SysRolesTable = &schema.Table{
		Name:       "sys_roles",
		Comment:    "角色表",
		Columns:    SysRolesColumns,
		PrimaryKey: []*schema.Column{SysRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_roles_sys_roles_children",
				Columns:    []*schema.Column{SysRolesColumns[16]},
				RefColumns: []*schema.Column{SysRolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "role_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysRolesColumns[9]},
			},
			{
				Name:    "idx_sys_role_name",
				Unique:  true,
				Columns: []*schema.Column{SysRolesColumns[10]},
			},
			{
				Name:    "idx_sys_role_code",
				Unique:  true,
				Columns: []*schema.Column{SysRolesColumns[11]},
			},
		},
	}
	// SysRoleAPIColumns holds the columns for the "sys_role_api" table.
	SysRoleAPIColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "role_id", Type: field.TypeUint32, Comment: "角色ID"},
		{Name: "api_id", Type: field.TypeUint32, Comment: "API ID"},
	}
	// SysRoleAPITable holds the schema information for the "sys_role_api" table.
	SysRoleAPITable = &schema.Table{
		Name:       "sys_role_api",
		Comment:    "角色 - API关联表",
		Columns:    SysRoleAPIColumns,
		PrimaryKey: []*schema.Column{SysRoleAPIColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_sys_role_api_role_id_api_id",
				Unique:  true,
				Columns: []*schema.Column{SysRoleAPIColumns[7], SysRoleAPIColumns[8]},
			},
			{
				Name:    "idx_sys_role_api_role_id",
				Unique:  false,
				Columns: []*schema.Column{SysRoleAPIColumns[7]},
			},
		},
	}
	// SysRoleMenuColumns holds the columns for the "sys_role_menu" table.
	SysRoleMenuColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "role_id", Type: field.TypeUint32, Comment: "角色ID"},
		{Name: "menu_id", Type: field.TypeUint32, Comment: "菜单ID"},
	}
	// SysRoleMenuTable holds the schema information for the "sys_role_menu" table.
	SysRoleMenuTable = &schema.Table{
		Name:       "sys_role_menu",
		Comment:    "角色 - 菜单关联表",
		Columns:    SysRoleMenuColumns,
		PrimaryKey: []*schema.Column{SysRoleMenuColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_sys_role_menu_role_id_menu_id",
				Unique:  true,
				Columns: []*schema.Column{SysRoleMenuColumns[7], SysRoleMenuColumns[8]},
			},
			{
				Name:    "idx_sys_role_menu_role_id",
				Unique:  false,
				Columns: []*schema.Column{SysRoleMenuColumns[7]},
			},
		},
	}
	// SysRolePermissionsColumns holds the columns for the "sys_role_permissions" table.
	SysRolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "role_id", Type: field.TypeUint32, Comment: "API资源ID（关联sys_api_resources.id）"},
		{Name: "permission_id", Type: field.TypeUint32, Comment: "权限ID（关联sys_permissions.id）"},
	}
	// SysRolePermissionsTable holds the schema information for the "sys_role_permissions" table.
	SysRolePermissionsTable = &schema.Table{
		Name:       "sys_role_permissions",
		Comment:    "角色 - 权限多对多关联表",
		Columns:    SysRolePermissionsColumns,
		PrimaryKey: []*schema.Column{SysRolePermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "rolepermission_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysRolePermissionsColumns[7]},
			},
			{
				Name:    "uix_perm_role",
				Unique:  true,
				Columns: []*schema.Column{SysRolePermissionsColumns[8], SysRolePermissionsColumns[9]},
			},
			{
				Name:    "uix_perm_role_tenant",
				Unique:  true,
				Columns: []*schema.Column{SysRolePermissionsColumns[7], SysRolePermissionsColumns[8]},
			},
		},
	}
	// SysTasksColumns holds the columns for the "sys_tasks" table.
	SysTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "type", Type: field.TypeEnum, Nullable: true, Comment: "任务类型", Enums: []string{"PERIODIC", "DELAY", "WAIT_RESULT"}, Default: "PERIODIC"},
		{Name: "type_name", Type: field.TypeString, Nullable: true, Comment: "任务执行类型名"},
		{Name: "task_payload", Type: field.TypeString, Nullable: true, Comment: "任务数据", SchemaType: map[string]string{"mysql": "json", "postgres": "jsonb"}},
		{Name: "cron_spec", Type: field.TypeString, Nullable: true, Comment: "cron表达式"},
		{Name: "task_options", Type: field.TypeJSON, Nullable: true, Comment: "任务选项"},
		{Name: "enable", Type: field.TypeBool, Nullable: true, Comment: "启用/禁用任务", Default: false},
	}
	// SysTasksTable holds the schema information for the "sys_tasks" table.
	SysTasksTable = &schema.Table{
		Name:       "sys_tasks",
		Comment:    "任务表",
		Columns:    SysTasksColumns,
		PrimaryKey: []*schema.Column{SysTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "task_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysTasksColumns[8]},
			},
			{
				Name:    "idx_sys_task_type_name",
				Unique:  true,
				Columns: []*schema.Column{SysTasksColumns[10]},
			},
		},
	}
	// SysTenantsColumns holds the columns for the "sys_tenants" table.
	SysTenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "name", Type: field.TypeString, Nullable: true, Comment: "租户名称"},
		{Name: "code", Type: field.TypeString, Nullable: true, Comment: "租户编号"},
		{Name: "logo_url", Type: field.TypeString, Nullable: true, Comment: "租户logo地址"},
		{Name: "industry", Type: field.TypeString, Nullable: true, Comment: "所属行业"},
		{Name: "admin_user_id", Type: field.TypeUint32, Nullable: true, Comment: "管理员用户ID"},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "租户状态", Enums: []string{"ON", "OFF", "EXPIRED", "FREEZE"}, Default: "ON"},
		{Name: "type", Type: field.TypeEnum, Nullable: true, Comment: "租户类型", Enums: []string{"TRIAL", "PAID", "INTERNAL", "PARTNER", "CUSTOM"}, Default: "PAID"},
		{Name: "audit_status", Type: field.TypeEnum, Nullable: true, Comment: "审核状态", Enums: []string{"PENDING", "APPROVED", "REJECTED"}},
		{Name: "subscription_at", Type: field.TypeTime, Nullable: true, Comment: "订阅时间"},
		{Name: "unsubscribe_at", Type: field.TypeTime, Nullable: true, Comment: "取消订阅时间"},
		{Name: "subscription_plan", Type: field.TypeString, Nullable: true, Comment: "订阅套餐"},
		{Name: "expired_at", Type: field.TypeTime, Nullable: true, Comment: "租户有效期"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true, Comment: "最后一次登录的时间"},
		{Name: "last_login_ip", Type: field.TypeString, Nullable: true, Comment: "最后一次登录的IP"},
	}
	// SysTenantsTable holds the schema information for the "sys_tenants" table.
	SysTenantsTable = &schema.Table{
		Name:       "sys_tenants",
		Comment:    "租户表",
		Columns:    SysTenantsColumns,
		PrimaryKey: []*schema.Column{SysTenantsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_sys_tenant_name",
				Unique:  true,
				Columns: []*schema.Column{SysTenantsColumns[8]},
			},
			{
				Name:    "idx_sys_tenant_code",
				Unique:  true,
				Columns: []*schema.Column{SysTenantsColumns[9]},
			},
			{
				Name:    "idx_sys_tenant_status_audit_status",
				Unique:  false,
				Columns: []*schema.Column{SysTenantsColumns[13], SysTenantsColumns[15]},
			},
			{
				Name:    "idx_sys_tenant_expired_at",
				Unique:  false,
				Columns: []*schema.Column{SysTenantsColumns[19]},
			},
		},
	}
	// SysUsersColumns holds the columns for the "sys_users" table.
	SysUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "username", Type: field.TypeString, Nullable: true, Comment: "用户名"},
		{Name: "nickname", Type: field.TypeString, Nullable: true, Comment: "昵称"},
		{Name: "realname", Type: field.TypeString, Nullable: true, Comment: "真实名字"},
		{Name: "email", Type: field.TypeString, Nullable: true, Size: 320, Comment: "电子邮箱"},
		{Name: "mobile", Type: field.TypeString, Nullable: true, Size: 255, Comment: "手机号码", Default: ""},
		{Name: "telephone", Type: field.TypeString, Nullable: true, Size: 255, Comment: "座机号码", Default: ""},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Comment: "头像"},
		{Name: "address", Type: field.TypeString, Nullable: true, Comment: "地址", Default: ""},
		{Name: "region", Type: field.TypeString, Nullable: true, Comment: "国家地区", Default: ""},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1023, Comment: "个人说明"},
		{Name: "gender", Type: field.TypeEnum, Nullable: true, Comment: "性别", Enums: []string{"SECRET", "MALE", "FEMALE"}, Default: "SECRET"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true, Comment: "最后一次登录的时间"},
		{Name: "last_login_ip", Type: field.TypeString, Nullable: true, Comment: "最后一次登录的IP"},
		{Name: "is_banned", Type: field.TypeBool, Nullable: true, Comment: "是否被禁用", Default: false},
	}
	// SysUsersTable holds the schema information for the "sys_users" table.
	SysUsersTable = &schema.Table{
		Name:       "sys_users",
		Comment:    "用户表",
		Columns:    SysUsersColumns,
		PrimaryKey: []*schema.Column{SysUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[8]},
			},
			{
				Name:    "idx_sys_user_username",
				Unique:  true,
				Columns: []*schema.Column{SysUsersColumns[9]},
			},
		},
	}
	// SysUserCredentialsColumns holds the columns for the "sys_user_credentials" table.
	SysUserCredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID"},
		{Name: "user_id", Type: field.TypeUint32, Nullable: true, Comment: "关联主表的用户ID"},
		{Name: "identity_type", Type: field.TypeEnum, Nullable: true, Comment: "认证方式类型", Enums: []string{"USERNAME", "USERID", "EMAIL", "PHONE", "SOCIAL_OAUTH", "ENTERPRISE_SSO", "IDENTITY_API_KEY", "DEVICE_ID", "CUSTOM"}, Default: "USERNAME"},
		{Name: "identifier", Type: field.TypeString, Nullable: true, Comment: "身份唯一标识符"},
		{Name: "credential_type", Type: field.TypeEnum, Nullable: true, Comment: "凭证类型", Enums: []string{"PASSWORD_HASH", "API_KEY", "API_SECRET", "ACCESS_TOKEN", "REFRESH_TOKEN", "JWT", "OAUTH_TOKEN", "OAUTH_AUTHORIZATION_CODE", "OAUTH_CLIENT_CREDENTIALS", "OTP", "TOTP", "SMS_OTP", "EMAIL_OTP", "HARDWARE_TOKEN", "SOFTWARE_TOKEN", "SECURITY_QUESTION", "BIOMETRIC", "BIOMETRIC_TOKEN", "SSO_TOKEN", "SAML_ASSERTION", "OPENID_CONNECT_ID_TOKEN", "SESSION_COOKIE", "TEMPORARY_CREDENTIAL", "CUSTOM", "RESERVED_FOR_FUTURE"}, Default: "PASSWORD_HASH"},
		{Name: "credential", Type: field.TypeString, Nullable: true, Comment: "凭证"},
		{Name: "is_primary", Type: field.TypeBool, Nullable: true, Comment: "是否主认证方式", Default: false},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Comment: "凭证状态", Enums: []string{"DISABLED", "ENABLED", "EXPIRED", "UNVERIFIED", "REMOVED", "BLOCKED", "TEMPORARY"}, Default: "ENABLED"},
		{Name: "extra_info", Type: field.TypeString, Nullable: true, Comment: "扩展信息", SchemaType: map[string]string{"mysql": "json", "postgres": "jsonb"}},
		{Name: "provider", Type: field.TypeString, Nullable: true, Comment: "第三方平台标识"},
		{Name: "provider_account_id", Type: field.TypeString, Nullable: true, Comment: "第三方平台的账号唯一ID"},
		{Name: "activate_token_hash", Type: field.TypeString, Nullable: true, Size: 255, Comment: "激活令牌哈希（不要存明文）"},
		{Name: "activate_token_expires_at", Type: field.TypeTime, Nullable: true, Comment: "激活令牌到期时间"},
		{Name: "activate_token_used_at", Type: field.TypeTime, Nullable: true, Comment: "激活令牌使用时间，单次使用时记录"},
		{Name: "reset_token_hash", Type: field.TypeString, Nullable: true, Size: 255, Comment: "重置密码令牌哈希（不要存明文）"},
		{Name: "reset_token_expires_at", Type: field.TypeTime, Nullable: true, Comment: "重置令牌到期时间"},
		{Name: "reset_token_used_at", Type: field.TypeTime, Nullable: true, Comment: "重置令牌使用时间"},
	}
	// SysUserCredentialsTable holds the schema information for the "sys_user_credentials" table.
	SysUserCredentialsTable = &schema.Table{
		Name:       "sys_user_credentials",
		Comment:    "用户认证信息表",
		Columns:    SysUserCredentialsColumns,
		PrimaryKey: []*schema.Column{SysUserCredentialsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "usercredential_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserCredentialsColumns[4]},
			},
			{
				Name:    "idx_sys_user_credential_uid_identity_identifier",
				Unique:  true,
				Columns: []*schema.Column{SysUserCredentialsColumns[5], SysUserCredentialsColumns[6], SysUserCredentialsColumns[7]},
			},
			{
				Name:    "idx_sys_user_credential_identifier",
				Unique:  false,
				Columns: []*schema.Column{SysUserCredentialsColumns[7]},
			},
			{
				Name:    "idx_sys_user_credential_user_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserCredentialsColumns[5]},
			},
			{
				Name:    "idx_sys_user_credential_provider_account",
				Unique:  true,
				Columns: []*schema.Column{SysUserCredentialsColumns[13], SysUserCredentialsColumns[14]},
			},
			{
				Name:    "idx_sys_user_credential_provider",
				Unique:  false,
				Columns: []*schema.Column{SysUserCredentialsColumns[13]},
			},
			{
				Name:    "idx_sys_user_credential_user_provider",
				Unique:  false,
				Columns: []*schema.Column{SysUserCredentialsColumns[5], SysUserCredentialsColumns[13]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysAdminLoginLogsTable,
		SysAdminLoginRestrictionsTable,
		SysAdminOperationLogsTable,
		SysAPIResourcesTable,
		SysDictEntriesTable,
		SysDictTypesTable,
		FilesTable,
		InternalMessagesTable,
		InternalMessageCategoriesTable,
		InternalMessageRecipientsTable,
		SysLanguagesTable,
		SysMembershipsTable,
		SysMembershipOrgUnitsTable,
		SysMembershipPositionsTable,
		SysMembershipRolesTable,
		SysMenusTable,
		SysOrgUnitsTable,
		SysPermissionsTable,
		SysPermissionAPIResourcesTable,
		SysPermissionMenusTable,
		SysPositionsTable,
		SysRolesTable,
		SysRoleAPITable,
		SysRoleMenuTable,
		SysRolePermissionsTable,
		SysTasksTable,
		SysTenantsTable,
		SysUsersTable,
		SysUserCredentialsTable,
	}
)

func init() {
	SysAdminLoginLogsTable.Annotation = &entsql.Annotation{
		Table:     "sys_admin_login_logs",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysAdminLoginRestrictionsTable.Annotation = &entsql.Annotation{
		Table:     "sys_admin_login_restrictions",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysAdminOperationLogsTable.Annotation = &entsql.Annotation{
		Table:     "sys_admin_operation_logs",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysAPIResourcesTable.Annotation = &entsql.Annotation{
		Table:     "sys_api_resources",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysDictEntriesTable.ForeignKeys[0].RefTable = SysDictTypesTable
	SysDictEntriesTable.Annotation = &entsql.Annotation{
		Table:     "sys_dict_entries",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysDictTypesTable.Annotation = &entsql.Annotation{
		Table:     "sys_dict_types",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	FilesTable.Annotation = &entsql.Annotation{
		Table:     "files",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	InternalMessagesTable.Annotation = &entsql.Annotation{
		Table:     "internal_messages",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	InternalMessageCategoriesTable.ForeignKeys[0].RefTable = InternalMessageCategoriesTable
	InternalMessageCategoriesTable.Annotation = &entsql.Annotation{
		Table:     "internal_message_categories",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	InternalMessageRecipientsTable.Annotation = &entsql.Annotation{
		Table:     "internal_message_recipients",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysLanguagesTable.Annotation = &entsql.Annotation{
		Table:     "sys_languages",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysMembershipsTable.Annotation = &entsql.Annotation{
		Table:     "sys_memberships",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysMembershipOrgUnitsTable.Annotation = &entsql.Annotation{
		Table:     "sys_membership_org_units",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysMembershipPositionsTable.Annotation = &entsql.Annotation{
		Table:     "sys_membership_positions",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysMembershipRolesTable.Annotation = &entsql.Annotation{
		Table:     "sys_membership_roles",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysMenusTable.ForeignKeys[0].RefTable = SysMenusTable
	SysMenusTable.Annotation = &entsql.Annotation{
		Table:     "sys_menus",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysOrgUnitsTable.ForeignKeys[0].RefTable = SysOrgUnitsTable
	SysOrgUnitsTable.Annotation = &entsql.Annotation{
		Table:     "sys_org_units",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysPermissionsTable.ForeignKeys[0].RefTable = SysPermissionsTable
	SysPermissionsTable.Annotation = &entsql.Annotation{
		Table:     "sys_permissions",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysPermissionAPIResourcesTable.Annotation = &entsql.Annotation{
		Table:     "sys_permission_api_resources",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysPermissionMenusTable.Annotation = &entsql.Annotation{
		Table:     "sys_permission_menus",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysPositionsTable.ForeignKeys[0].RefTable = SysPositionsTable
	SysPositionsTable.Annotation = &entsql.Annotation{
		Table:     "sys_positions",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysRolesTable.ForeignKeys[0].RefTable = SysRolesTable
	SysRolesTable.Annotation = &entsql.Annotation{
		Table:     "sys_roles",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysRoleAPITable.Annotation = &entsql.Annotation{
		Table:     "sys_role_api",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysRoleMenuTable.Annotation = &entsql.Annotation{
		Table:     "sys_role_menu",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysRolePermissionsTable.Annotation = &entsql.Annotation{
		Table:     "sys_role_permissions",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysTasksTable.Annotation = &entsql.Annotation{
		Table:     "sys_tasks",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysTenantsTable.Annotation = &entsql.Annotation{
		Table:     "sys_tenants",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysUsersTable.Annotation = &entsql.Annotation{
		Table:     "sys_users",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SysUserCredentialsTable.Annotation = &entsql.Annotation{
		Table:     "sys_user_credentials",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
}
