// This file is auto-generated by protoc-gen-typescript-http and should not be edited manually.
export * from "./generated/admin/service/v1/index";

export * from "./auth";
export * from "./user";
export * from "./admin-portal";
export * from "./user-profile";
export * from "./file-transfer";
export * from "./dict";
